echo "Generating TestResults/DiffUseMREs/formalarray.B.out"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/formalarray.B > TestResults/DiffUseMREs/formalarray.B.out
echo "Generating TestResults/DiffUseMREs/formalstructpointer.B.out"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/formalstructpointer.B > TestResults/DiffUseMREs/formalstructpointer.B.out
echo "Generating TestResults/DiffUseMREs/localpointerToscalar.B.out"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/localpointerToscalar.B > TestResults/DiffUseMREs/localpointerToscalar.B.out
echo "Generating TestResults/DiffUseMREs/formalpointerToArray.B.out"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/formalpointerToArray.B > TestResults/DiffUseMREs/formalpointerToArray.B.out
echo "Generating TestResults/DiffUseMREs/formalstructvar.B.out"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/formalstructvar.B > TestResults/DiffUseMREs/formalstructvar.B.out
echo "Generating TestResults/DiffUseMREs/localscalar.B.out"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/localscalar.B > TestResults/DiffUseMREs/localscalar.B.out
echo "Generating TestResults/DiffUseMREs/formalpointerToscalar.B.out"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/formalpointerToscalar.B > TestResults/DiffUseMREs/formalpointerToscalar.B.out
echo "Generating TestResults/DiffUseMREs/localarray.B.out"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/localarray.B > TestResults/DiffUseMREs/localarray.B.out
echo "Generating TestResults/DiffUseMREs/localstructpointer.B.out"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/localstructpointer.B > TestResults/DiffUseMREs/localstructpointer.B.out
echo "Generating TestResults/DiffUseMREs/formalscalar.B.out"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/formalscalar.B > TestResults/DiffUseMREs/formalscalar.B.out
echo "Generating TestResults/DiffUseMREs/localpointerToArray.B.out"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/localpointerToArray.B > TestResults/DiffUseMREs/localpointerToArray.B.out
echo "Generating TestResults/DiffUseMREs/localstructvar.B.out"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/localstructvar.B > TestResults/DiffUseMREs/localstructvar.B.out
