echo "Generating TestResults/ICFGVaryInActive/simple1.B.out"
./test-open64 --oa-ICFGActivity TestCases/Activity/simple1.B > TestResults/ICFGVaryInActive/simple1.B.out
echo "Generating TestResults/ICFGVaryInActive/simple2.B.out"
./test-open64 --oa-ICFGActivity TestCases/Activity/simple2.B > TestResults/ICFGVaryInActive/simple2.B.out
echo "Generating TestResults/ICFGVaryInActive/simple3.B.out"
./test-open64 --oa-ICFGActivity TestCases/Activity/simple3.B > TestResults/ICFGVaryInActive/simple3.B.out
echo "Generating TestResults/ICFGVaryInActive/simple3np.B.out"
./test-open64 --oa-ICFGActivity TestCases/Activity/simple3np.B > TestResults/ICFGVaryInActive/simple3np.B.out
echo "Generating TestResults/ICFGVaryInActive/simple_if1.B.out"
./test-open64 --oa-ICFGActivity TestCases/Activity/simple_if1.B > TestResults/ICFGVaryInActive/simple_if1.B.out
echo "Generating TestResults/ICFGVaryInActive/simple_if2.B.out"
./test-open64 --oa-ICFGActivity TestCases/Activity/simple_if2.B > TestResults/ICFGVaryInActive/simple_if2.B.out
echo "Generating TestResults/ICFGVaryInActive/activity_int6.B.out"
./test-open64 --oa-ICFGActivity TestCases/Activity/activity_int6.B > TestResults/ICFGVaryInActive/activity_int6.B.out
echo "Generating TestResults/ICFGVaryInActive/activity_nested1.B.out"
./test-open64 --oa-ICFGActivity TestCases/Activity/activity_nested1.B > TestResults/ICFGVaryInActive/activity_nested1.B.out
echo "Generating TestResults/ICFGVaryInActive/activity_proc_call1.B.out"
./test-open64 --oa-ICFGActivity TestCases/Activity/activity_proc_call1.B > TestResults/ICFGVaryInActive/activity_proc_call1.B.out
echo "Generating TestResults/ICFGVaryInActive/activity_proc_call4.B.out"
./test-open64 --oa-ICFGActivity TestCases/Activity/activity_proc_call4.B > TestResults/ICFGVaryInActive/activity_proc_call4.B.out
