echo "Generating TestResults/UseMREs/formalarray.B.out"
./test-open64 --oa-UseMREs TestCases/UseMREs/formalarray.B > TestResults/UseMREs/formalarray.B.out
echo "Generating TestResults/UseMREs/formalstructpointer.B.out"
./test-open64 --oa-UseMREs TestCases/UseMREs/formalstructpointer.B > TestResults/UseMREs/formalstructpointer.B.out
echo "Generating TestResults/UseMREs/localpointerToscalar.B.out"
./test-open64 --oa-UseMREs TestCases/UseMREs/localpointerToscalar.B > TestResults/UseMREs/localpointerToscalar.B.out
echo "Generating TestResults/UseMREs/formalpointerToArray.B.out"
./test-open64 --oa-UseMREs TestCases/UseMREs/formalpointerToArray.B > TestResults/UseMREs/formalpointerToArray.B.out
echo "Generating TestResults/UseMREs/formalstructvar.B.out"
./test-open64 --oa-UseMREs TestCases/UseMREs/formalstructvar.B > TestResults/UseMREs/formalstructvar.B.out
echo "Generating TestResults/UseMREs/localscalar.B.out"
./test-open64 --oa-UseMREs TestCases/UseMREs/localscalar.B > TestResults/UseMREs/localscalar.B.out
echo "Generating TestResults/UseMREs/formalpointerToscalar.B.out"
./test-open64 --oa-UseMREs TestCases/UseMREs/formalpointerToscalar.B > TestResults/UseMREs/formalpointerToscalar.B.out
echo "Generating TestResults/UseMREs/localarray.B.out"
./test-open64 --oa-UseMREs TestCases/UseMREs/localarray.B > TestResults/UseMREs/localarray.B.out
echo "Generating TestResults/UseMREs/localstructpointer.B.out"
./test-open64 --oa-UseMREs TestCases/UseMREs/localstructpointer.B > TestResults/UseMREs/localstructpointer.B.out
echo "Generating TestResults/UseMREs/formalscalar.B.out"
./test-open64 --oa-UseMREs TestCases/UseMREs/formalscalar.B > TestResults/UseMREs/formalscalar.B.out
echo "Generating TestResults/UseMREs/localpointerToArray.B.out"
./test-open64 --oa-UseMREs TestCases/UseMREs/localpointerToArray.B > TestResults/UseMREs/localpointerToArray.B.out
echo "Generating TestResults/UseMREs/localstructvar.B.out"
./test-open64 --oa-UseMREs TestCases/UseMREs/localstructvar.B > TestResults/UseMREs/localstructvar.B.out
