echo "Testing TestCases/DiffUseMREs/formalarray.B, TestResults/DiffUseMREs/formalarray.B.out Checked by PLM 10/15/07"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/formalarray.B > t
diff t TestResults/DiffUseMREs/formalarray.B.out

echo "Testing TestCases/DiffUseMREs/formalstructpointer.B, TestResults/DiffUseMREs/formalstructpointer.B.out Checked by PLM 10/15/07"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/formalstructpointer.B > t
diff t TestResults/DiffUseMREs/formalstructpointer.B.out

echo "Testing TestCases/DiffUseMREs/localpointerToscalar.B, TestResults/DiffUseMREs/localpointerToscalar.B.out Checked by PLM 10/15/07"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/localpointerToscalar.B > t
diff t TestResults/DiffUseMREs/localpointerToscalar.B.out

echo "Testing TestCases/DiffUseMREs/formalpointerToArray.B, TestResults/DiffUseMREs/formalpointerToArray.B.out Checked by PLM 10/15/07"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/formalpointerToArray.B > t
diff t TestResults/DiffUseMREs/formalpointerToArray.B.out

echo "Testing TestCases/DiffUseMREs/formalstructvar.B, TestResults/DiffUseMREs/formalstructvar.B.out Checked by PLM 10/15/07"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/formalstructvar.B > t
diff t TestResults/DiffUseMREs/formalstructvar.B.out

echo "Testing TestCases/DiffUseMREs/localscalar.B, TestResults/DiffUseMREs/localscalar.B.out Checked by PLM 10/15/07"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/localscalar.B > t
diff t TestResults/DiffUseMREs/localscalar.B.out

echo "Testing TestCases/DiffUseMREs/formalpointerToscalar.B, TestResults/DiffUseMREs/formalpointerToscalar.B.out Checked by PLM 10/15/07"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/formalpointerToscalar.B > t
diff t TestResults/DiffUseMREs/formalpointerToscalar.B.out

echo "Testing TestCases/DiffUseMREs/localarray.B, TestResults/DiffUseMREs/localarray.B.out Checked by PLM 10/15/07"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/localarray.B > t
diff t TestResults/DiffUseMREs/localarray.B.out

echo "Testing TestCases/DiffUseMREs/localstructpointer.B, TestResults/DiffUseMREs/localstructpointer.B.out Checked by PLM 10/15/07"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/localstructpointer.B > t
diff t TestResults/DiffUseMREs/localstructpointer.B.out

echo "Testing TestCases/DiffUseMREs/formalscalar.B, TestResults/DiffUseMREs/formalscalar.B.out Checked by PLM 10/15/07"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/formalscalar.B > t
diff t TestResults/DiffUseMREs/formalscalar.B.out

echo "Testing TestCases/DiffUseMREs/localpointerToArray.B, TestResults/DiffUseMREs/localpointerToArray.B.out Checked by PLM 10/15/07"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/localpointerToArray.B > t
diff t TestResults/DiffUseMREs/localpointerToArray.B.out

echo "Testing TestCases/DiffUseMREs/localstructvar.B, TestResults/DiffUseMREs/localstructvar.B.out Checked by PLM 10/15/07"
./test-open64 --oa-DiffUseMREs TestCases/DiffUseMREs/localstructvar.B > t
diff t TestResults/DiffUseMREs/localstructvar.B.out

