echo "Testing TestCases/AssignPairs/SimpleBalanced.B, TestResults/AssignPairs/SimpleBalanced.B.out Checked by LMR 10/24/06"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/SimpleBalanced.B > t
diff t TestResults/AssignPairs/SimpleBalanced.B.out

echo "Testing TestCases/AssignPairs/SimpleUnbalanced.B, TestResults/AssignPairs/SimpleUnbalanced.B.out Checked by LMR 10/24/06"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/SimpleUnbalanced.B > t
diff t TestResults/AssignPairs/SimpleUnbalanced.B.out

echo "Testing TestCases/AssignPairs/SimpleCall.B, TestResults/AssignPairs/SimpleCall.B.out Checked by LMR 10/24/06"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/SimpleCall.B > t
diff t TestResults/AssignPairs/SimpleCall.B.out

echo "Testing TestCases/AssignPairs/SimpleSin.B, TestResults/AssignPairs/SimpleSin.B.out Checked by LMR 10/24/06"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/SimpleSin.B > t
diff t TestResults/AssignPairs/SimpleSin.B.out

echo "Testing TestCases/AssignPairs/ExprCall.B, TestResults/AssignPairs/ExprCall.B.out Checked by LMR 10/24/06"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/ExprCall.B > t
diff t TestResults/AssignPairs/ExprCall.B.out

echo "Testing TestCases/AssignPairs/ExprCallf.B, TestResults/AssignPairs/ExprCallf.B.out Checked by LMR 10/24/06"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/ExprCallf.B > t
diff t TestResults/AssignPairs/ExprCallf.B.out

echo "Testing TestCases/AssignPairs/ExprCallIntent.B, TestResults/AssignPairs/ExprCallIntent.B.out Checked by LMR 10/24/06"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/ExprCallIntent.B > t
diff t TestResults/AssignPairs/ExprCallIntent.B.out

echo "Testing TestCases/AssignPairs/SinExpr.B, TestResults/AssignPairs/SinExpr.B.out Checked by LMR 11/09/06"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/SinExpr.B > t
diff t TestResults/AssignPairs/SinExpr.B.out

echo "Testing TestCases/AssignPairs/SinFuncExpr.B, TestResults/AssignPairs/SinFuncExpr.B.out Checked by LMR 11/09/06"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/SinFuncExpr.B > t
diff t TestResults/AssignPairs/SinFuncExpr.B.out

echo "Testing TestCases/AssignPairs/CosDeg2Rad.B, TestResults/AssignPairs/CosDeg2Rad.B.out Checked by LMR 12/07/06"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/CosDeg2Rad.B > t
diff t TestResults/AssignPairs/CosDeg2Rad.B.out

echo "Testing TestCases/AssignPairs/integer_assignment.B, TestResults/AssignPairs/integer_assignment.B.out Checked by PLM 08/15/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/integer_assignment.B > t
diff t TestResults/AssignPairs/integer_assignment.B.out

echo "Testing TestCases/AssignPairs/array_assignment.B, TestResults/AssignPairs/array_assignment.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/array_assignment.B > t
diff t TestResults/AssignPairs/array_assignment.B.out

echo "Testing TestCases/AssignPairs/arraysection_assignment.B, TestResults/AssignPairs/arraysection_assignment.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/arraysection_assignment.B > t
diff t TestResults/AssignPairs/arraysection_assignment.B.out

echo "Testing TestCases/AssignPairs/complex_statement.B, TestResults/AssignPairs/complex_statement.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/complex_statement.B > t
diff t TestResults/AssignPairs/complex_statement.B.out

echo "Testing TestCases/AssignPairs/constant_variable_expression.B, TestResults/AssignPairs/constant_variable_expression.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/constant_variable_expression.B > t
diff t TestResults/AssignPairs/constant_variable_expression.B.out

echo "Testing TestCases/AssignPairs/do_loop.B, TestResults/AssignPairs/do_loop.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/do_loop.B > t
diff t TestResults/AssignPairs/do_loop.B.out

echo "Testing TestCases/AssignPairs/double_dimension_array_assignment.B, TestResults/AssignPairs/double_dimension_array_assignment.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/double_dimension_array_assignment.B > t
diff t TestResults/AssignPairs/double_dimension_array_assignment.B.out

echo "Testing TestCases/AssignPairs/formalscalardef.B, TestResults/AssignPairs/formalscalardef.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/formalscalardef.B > t
diff t TestResults/AssignPairs/formalscalardef.B.out

echo "Testing TestCases/AssignPairs/formalscalaruse.B, TestResults/AssignPairs/formalscalaruse.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/formalscalaruse.B > t
diff t TestResults/AssignPairs/formalscalaruse.B.out

echo "Testing TestCases/AssignPairs/function_call.B, TestResults/AssignPairs/function_call.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/function_call.B > t
diff t TestResults/AssignPairs/function_call.B.out

echo "Testing TestCases/AssignPairs/function_return.B, TestResults/AssignPairs/function_return.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/function_return.B > t
diff t TestResults/AssignPairs/function_return.B.out

echo "Testing TestCases/AssignPairs/integer_assignment.B, TestResults/AssignPairs/integer_assignment.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/integer_assignment.B > t
diff t TestResults/AssignPairs/integer_assignment.B.out

echo "Testing TestCases/AssignPairs/integer_expression.B, TestResults/AssignPairs/integer_expression.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/integer_expression.B > t
diff t TestResults/AssignPairs/integer_expression.B.out

echo "Testing TestCases/AssignPairs/intrinsic.B, TestResults/AssignPairs/intrinsic.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/intrinsic.B > t
diff t TestResults/AssignPairs/intrinsic.B.out

echo "Testing TestCases/AssignPairs/intrinsic_complex.B, TestResults/AssignPairs/intrinsic_complex.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/intrinsic_complex.B > t
diff t TestResults/AssignPairs/intrinsic_complex.B.out

echo "Testing TestCases/AssignPairs/intrinsic_expression.B, TestResults/AssignPairs/intrinsic_expression.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/intrinsic_expression.B > t
diff t TestResults/AssignPairs/intrinsic_expression.B.out

echo "Testing TestCases/AssignPairs/logical_assignment.B, TestResults/AssignPairs/logical_assignment.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/logical_assignment.B > t
diff t TestResults/AssignPairs/logical_assignment.B.out

echo "Testing TestCases/AssignPairs/real_assignment.B, TestResults/AssignPairs/real_assignment.B.out Checked by PLM 08/30/07"
./test-open64 --oa-AssignPairs TestCases/AssignPairs/real_assignment.B > t
diff t TestResults/AssignPairs/real_assignment.B.out

echo "Testing TestCases/AssignPairs/if.B, TestResults/AssignPairs/if.B.out "
./test-open64 --oa-AssignPairs TestCases/AssignPairs/if.B > t
diff t TestResults/AssignPairs/if.B.out

