echo "Testing TestCases/Alias/interalias_proc_call1.B, TestResults/AliasMapBasic/interalias_proc_call1.B.out not checked"
./test-open64 --oa-AliasMapBasic TestCases/Alias/interalias_proc_call1.B > t
diff t TestResults/AliasMapBasic/interalias_proc_call1.B.out

echo "Testing TestCases/Alias/interalias_proc_call2.B, TestResults/AliasMapBasic/interalias_proc_call2.B.out not checked"
./test-open64 --oa-AliasMapBasic TestCases/Alias/interalias_proc_call2.B > t
diff t TestResults/AliasMapBasic/interalias_proc_call2.B.out

echo "Testing TestCases/Alias/interalias_proc_call3.B, TestResults/AliasMapBasic/interalias_proc_call3.B.out not checked"
./test-open64 --oa-AliasMapBasic TestCases/Alias/interalias_proc_call3.B > t
diff t TestResults/AliasMapBasic/interalias_proc_call3.B.out

