echo "Generating TestResults/AliasMapXAIF/Alias_Pointer.B.out"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/Alias_Pointer.B > TestResults/AliasMapXAIF/Alias_Pointer.B.out
echo "Generating TestResults/AliasMapXAIF/NoAlias_StructVar.B.out"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_StructVar.B > TestResults/AliasMapXAIF/NoAlias_StructVar.B.out
echo "Generating TestResults/AliasMapXAIF/NoAlias_Named.B.out"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_Named.B > TestResults/AliasMapXAIF/NoAlias_Named.B.out
echo "Generating TestResults/AliasMapXAIF/NoAlias_Unnamed.B.out"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_Unnamed.B > TestResults/AliasMapXAIF/NoAlias_Unnamed.B.out
echo "Generating TestResults/AliasMapXAIF/NoAlias_FieldAccess.B.out"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_FieldAccess.B > TestResults/AliasMapXAIF/NoAlias_FieldAccess.B.out
echo "Generating TestResults/AliasMapXAIF/NoAlias_SubSet.B.out"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_SubSet.B > TestResults/AliasMapXAIF/NoAlias_SubSet.B.out
echo "Generating TestResults/AliasMapXAIF/Param_Alias.B.out"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/Param_Alias.B > TestResults/AliasMapXAIF/Param_Alias.B.out
echo "Generating TestResults/AliasMapXAIF/multiple_calls.B.out"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/multiple_calls.B > TestResults/AliasMapXAIF/multiple_calls.B.out
echo "Generating TestResults/AliasMapXAIF/pointer_to_local.B.out"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/pointer_to_local.B > TestResults/AliasMapXAIF/pointer_to_local.B.out
