echo "Generating TestResults/CSFIActive/activity_int5.B.out"
./test-open64 --oa-CSFIActivity TestCases/Activity/activity_int5.B > TestResults/CSFIActive/activity_int5.B.out
echo "Generating TestResults/CSFIActive/argumentArrayIndex3.B.out"
./test-open64 --oa-CSFIActivity TestCases/Activity/argumentArrayIndex3.B > TestResults/CSFIActive/argumentArrayIndex3.B.out
echo "Generating TestResults/CSFIActive/activity_proc_call1.B.out"
./test-open64 --oa-CSFIActivity TestCases/Activity/activity_proc_call1.B > TestResults/CSFIActive/activity_proc_call1.B.out
echo "Generating TestResults/CSFIActive/simple_if2.B.out"
./test-open64 --oa-CSFIActivity TestCases/Activity/simple_if2.B > TestResults/CSFIActive/simple_if2.B.out
echo "Generating TestResults/CSFIActive/sideEffect_3.B.out"
./test-open64 --oa-CSFIActivity TestCases/Activity/sideEffect_3.B > TestResults/CSFIActive/sideEffect_3.B.out
echo "Generating TestResults/CSFIActive/multiple_calls1.B.out"
./test-open64 --oa-CSFIActivity TestCases/Activity/multiple_calls1.B > TestResults/CSFIActive/multiple_calls1.B.out
echo "Generating TestResults/CSFIActive/multiple_calls2.B.out"
./test-open64 --oa-CSFIActivity TestCases/Activity/multiple_calls2.B > TestResults/CSFIActive/multiple_calls2.B.out
echo "Generating TestResults/CSFIActive/actualAsExpression.B.out"
./test-open64 --oa-CSFIActivity TestCases/Activity/actualAsExpression.B > TestResults/CSFIActive/actualAsExpression.B.out
