echo "Generating TestResults/ICFGDep/expressions.B.out"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/expressions.B > TestResults/ICFGDep/expressions.B.out
echo "Generating TestResults/ICFGDep/activity_int5.B.out"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/activity_int5.B > TestResults/ICFGDep/activity_int5.B.out
echo "Generating TestResults/ICFGDep/argumentArrayIndex3.B.out"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/argumentArrayIndex3.B > TestResults/ICFGDep/argumentArrayIndex3.B.out
echo "Generating TestResults/ICFGDep/globalActive_7.B.out"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/globalActive_7.B > TestResults/ICFGDep/globalActive_7.B.out
echo "Generating TestResults/ICFGDep/multiple_calls2.B.out"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/multiple_calls2.B > TestResults/ICFGDep/multiple_calls2.B.out
echo "Generating TestResults/ICFGDep/parameters.B.out"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/parameters.B > TestResults/ICFGDep/parameters.B.out
echo "Generating TestResults/ICFGDep/simple_if2.B.out"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/simple_if2.B > TestResults/ICFGDep/simple_if2.B.out
echo "Generating TestResults/ICFGDep/activity_proc_call1.B.out"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/activity_proc_call1.B > TestResults/ICFGDep/activity_proc_call1.B.out
echo "Generating TestResults/ICFGDep/multiple_calls1.B.out"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/multiple_calls1.B > TestResults/ICFGDep/multiple_calls1.B.out
echo "Generating TestResults/ICFGDep/nested_calls_4.B.out"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/nested_calls_4.B > TestResults/ICFGDep/nested_calls_4.B.out
echo "Generating TestResults/ICFGDep/sideEffect_3.B.out"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/sideEffect_3.B > TestResults/ICFGDep/sideEffect_3.B.out
