echo "Generating TestResults/MemRefExpr/nested.B.out"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/nested.B > TestResults/MemRefExpr/nested.B.out
echo "Generating TestResults/MemRefExpr/local.B.out"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/local.B > TestResults/MemRefExpr/local.B.out
echo "Generating TestResults/MemRefExpr/global.B.out"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/global.B > TestResults/MemRefExpr/global.B.out
echo "Generating TestResults/MemRefExpr/module.B.out"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/module.B > TestResults/MemRefExpr/module.B.out
