echo "Generating TestResults/ReachConsts/constprop_if1a.B.out"
./test-open64 --oa-ReachConsts TestCases/ReachConsts/constprop_if1a.B > TestResults/ReachConsts/constprop_if1a.B.out
echo "Generating TestResults/ReachConsts/constprop_if1.B.out"
./test-open64 --oa-ReachConsts TestCases/ReachConsts/constprop_if1.B > TestResults/ReachConsts/constprop_if1.B.out
echo "Generating TestResults/ReachConsts/constprop_if1b.B.out"
./test-open64 --oa-ReachConsts TestCases/ReachConsts/constprop_if1b.B > TestResults/ReachConsts/constprop_if1b.B.out
echo "Generating TestResults/ReachConsts/constprop_if1c.B.out"
./test-open64 --oa-ReachConsts TestCases/ReachConsts/constprop_if1c.B > TestResults/ReachConsts/constprop_if1c.B.out
echo "Generating TestResults/ReachConsts/constprop_loop1.B.out"
./test-open64 --oa-ReachConsts TestCases/ReachConsts/constprop_loop1.B > TestResults/ReachConsts/constprop_loop1.B.out
echo "Generating TestResults/ReachConsts/constprop_loop2.B.out"
./test-open64 --oa-ReachConsts TestCases/ReachConsts/constprop_loop2.B > TestResults/ReachConsts/constprop_loop2.B.out
