${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/Alias_Pointer.f
mv Alias_Pointer.B TestCases/AliasMapXAIF/Alias_Pointer.B
echo "Testing TestCases/AliasMapXAIF/Alias_Pointer.B, TestResults/AliasMapXAIF/Alias_Pointer.B.out Checked by PLM 05/04/08"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/Alias_Pointer.B > t
diff -I "LOC 0 0 source files:" t TestResults/AliasMapXAIF/Alias_Pointer.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/NoAlias_StructVar.f
mv NoAlias_StructVar.B TestCases/AliasMapXAIF/NoAlias_StructVar.B
echo "Testing TestCases/AliasMapXAIF/NoAlias_StructVar.B, TestResults/AliasMapXAIF/NoAlias_StructVar.B.out Checked by PLM 05/04/08"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_StructVar.B > t
diff -I "LOC 0 0 source files:" t TestResults/AliasMapXAIF/NoAlias_StructVar.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/NoAlias_Named.f
mv NoAlias_Named.B TestCases/AliasMapXAIF/NoAlias_Named.B
echo "Testing TestCases/AliasMapXAIF/NoAlias_Named.B, TestResults/AliasMapXAIF/NoAlias_Named.B.out Checked by PLM 05/04/08"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_Named.B > t
diff -I "LOC 0 0 source files:" t TestResults/AliasMapXAIF/NoAlias_Named.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/NoAlias_Unnamed.f
mv NoAlias_Unnamed.B TestCases/AliasMapXAIF/NoAlias_Unnamed.B
echo "Testing TestCases/AliasMapXAIF/NoAlias_Unnamed.B, TestResults/AliasMapXAIF/NoAlias_Unnamed.B.out Checked by PLM 05/04/08"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_Unnamed.B > t
diff -I "LOC 0 0 source files:" t TestResults/AliasMapXAIF/NoAlias_Unnamed.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/NoAlias_FieldAccess.f
mv NoAlias_FieldAccess.B TestCases/AliasMapXAIF/NoAlias_FieldAccess.B
echo "Testing TestCases/AliasMapXAIF/NoAlias_FieldAccess.B, TestResults/AliasMapXAIF/NoAlias_FieldAccess.B.out Checked by PLM 05/04/08"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_FieldAccess.B > t
diff -I "LOC 0 0 source files:" t TestResults/AliasMapXAIF/NoAlias_FieldAccess.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/NoAlias_SubSet.f
mv NoAlias_SubSet.B TestCases/AliasMapXAIF/NoAlias_SubSet.B
echo "Testing TestCases/AliasMapXAIF/NoAlias_SubSet.B, TestResults/AliasMapXAIF/NoAlias_SubSet.B.out Checked by PLM 05/04/08"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_SubSet.B > t
diff -I "LOC 0 0 source files:" t TestResults/AliasMapXAIF/NoAlias_SubSet.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/Param_Alias.f
mv Param_Alias.B TestCases/AliasMapXAIF/Param_Alias.B
echo "Testing TestCases/AliasMapXAIF/Param_Alias.B, TestResults/AliasMapXAIF/Param_Alias.B.out Checked by PLM 05/04/08"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/Param_Alias.B > t
diff -I "LOC 0 0 source files:" t TestResults/AliasMapXAIF/Param_Alias.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/multiple_calls.f
mv multiple_calls.B TestCases/AliasMapXAIF/multiple_calls.B
echo "Testing TestCases/AliasMapXAIF/multiple_calls.B, TestResults/AliasMapXAIF/multiple_calls.B.out Checked by PLM 05/04/08"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/multiple_calls.B > t
diff -I "LOC 0 0 source files:" t TestResults/AliasMapXAIF/multiple_calls.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/pointer_to_local.f
mv pointer_to_local.B TestCases/AliasMapXAIF/pointer_to_local.B
echo "Testing TestCases/AliasMapXAIF/pointer_to_local.B, TestResults/AliasMapXAIF/pointer_to_local.B.out Checked by PLM 05/04/08"
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/pointer_to_local.B > t
diff -I "LOC 0 0 source files:" t TestResults/AliasMapXAIF/pointer_to_local.B.out

