echo "Testing TestCases/Activity/sac07//CG/cg_1_mpig.B, TestResults/sac07ICFGActive/CG/cg_1_mpig.B.out "
./test-open64 --oa-sac07ICFGActivity TestCases/Activity/sac07//CG/cg_1_mpig.B > t
diff t TestResults/sac07ICFGActive/CG/cg_1_mpig.B.out

echo "Testing TestCases/Activity/sac07//adiabatic/adiabatic2.B, TestResults/sac07ICFGActive/adiabatic/adiabatic2.B.out "
./test-open64 --oa-sac07ICFGActivity TestCases/Activity/sac07//adiabatic/adiabatic2.B > t
diff t TestResults/sac07ICFGActive/adiabatic/adiabatic2.B.out

echo "Testing TestCases/Activity/sac07//msa/msa.B, TestResults/sac07ICFGActive/msa/msa.B.out "
./test-open64 --oa-sac07ICFGActivity TestCases/Activity/sac07//msa/msa.B > t
diff t TestResults/sac07ICFGActive/msa/msa.B.out

echo "Testing TestCases/Activity/sac07//swirl/swirl.B, TestResults/sac07ICFGActive/swirl/swirl.B.out "
./test-open64 --oa-sac07ICFGActivity TestCases/Activity/sac07//swirl/swirl.B > t
diff t TestResults/sac07ICFGActive/swirl/swirl.B.out

echo "Testing TestCases/Activity/sac07//c2/c2.B, TestResults/sac07ICFGActive/c2/c2.B.out "
./test-open64 --oa-sac07ICFGActivity TestCases/Activity/sac07//c2/c2.B > t
diff t TestResults/sac07ICFGActive/c2/c2.B.out

