echo "Testing TestCases/Activity/activity_int5.B, TestResults/ICFGActive/activity_int5.B.out Tested by PLM 04/04/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/activity_int5.B > t
diff t TestResults/ICFGActive/activity_int5.B.out

echo "Testing TestCases/Activity/argumentArrayIndex3.B, TestResults/ICFGActive/argumentArrayIndex3.B.out Tested by PLM 04/04/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/argumentArrayIndex3.B > t
diff t TestResults/ICFGActive/argumentArrayIndex3.B.out

echo "Testing TestCases/Activity/activity_proc_call1.B, TestResults/ICFGActive/activity_proc_call1.B.out Tested by PLM 04/04/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/activity_proc_call1.B > t
diff t TestResults/ICFGActive/activity_proc_call1.B.out

echo "Testing TestCases/Activity/simple_if2.B, TestResults/ICFGActive/simple_if2.B.out Tested by PLM 04/04/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/simple_if2.B > t
diff t TestResults/ICFGActive/simple_if2.B.out

