echo "Testing TestCases/ICFGDep/expressions.B, TestResults/ICFGDep/expressions.B.out checked by PLM 02/18/08"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/expressions.B > t
diff t TestResults/ICFGDep/expressions.B.out

echo "Testing TestCases/ICFGDep/activity_int5.B, TestResults/ICFGDep/activity_int5.B.out checked by PLM 02/18/08"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/activity_int5.B > t
diff t TestResults/ICFGDep/activity_int5.B.out

echo "Testing TestCases/ICFGDep/interalias_proc_call7.B, TestResults/ICFGDep/interalias_proc_call7.B.out checked by PLM 02/18/08"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/interalias_proc_call7.B > t
diff t TestResults/ICFGDep/interalias_proc_call7.B.out

echo "Testing TestCases/ICFGDep/globalActive_7.B, TestResults/ICFGDep/globalActive_7.B.out checked by PLM 02/18/08"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/globalActive_7.B > t
diff t TestResults/ICFGDep/globalActive_7.B.out

echo "Testing TestCases/ICFGDep/multiple_calls2.B, TestResults/ICFGDep/multiple_calls2.B.out checked by PLM 02/18/08"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/multiple_calls2.B > t
diff t TestResults/ICFGDep/multiple_calls2.B.out

echo "Testing TestCases/ICFGDep/parameters.B, TestResults/ICFGDep/parameters.B.out checked by PLM 02/18/08"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/parameters.B > t
diff t TestResults/ICFGDep/parameters.B.out

echo "Testing TestCases/ICFGDep/simple_if2.B, TestResults/ICFGDep/simple_if2.B.out checked by PLM 02/18/08"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/simple_if2.B > t
diff t TestResults/ICFGDep/simple_if2.B.out

echo "Testing TestCases/ICFGDep/activity_proc_call1.B, TestResults/ICFGDep/activity_proc_call1.B.out checked by PLM 02/18/08"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/activity_proc_call1.B > t
diff t TestResults/ICFGDep/activity_proc_call1.B.out

echo "Testing TestCases/ICFGDep/multiple_calls1.B, TestResults/ICFGDep/multiple_calls1.B.out checked by PLM 02/18/08"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/multiple_calls1.B > t
diff t TestResults/ICFGDep/multiple_calls1.B.out

echo "Testing TestCases/ICFGDep/nested_calls_4.B, TestResults/ICFGDep/nested_calls_4.B.out checked by PLM 02/18/08"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/nested_calls_4.B > t
diff t TestResults/ICFGDep/nested_calls_4.B.out

echo "Testing TestCases/ICFGDep/sideEffect_3.B, TestResults/ICFGDep/sideEffect_3.B.out checked by PLM 02/18/08"
./test-open64 --oa-ICFGDep TestCases/ICFGDep/sideEffect_3.B > t
diff t TestResults/ICFGDep/sideEffect_3.B.out

