echo "Testing TestCases/Activity/activity_int5.B, TestResults/ICFGActive/activity_int5.B.out Tested by PLM 05/02/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/activity_int5.B > t
diff t TestResults/ICFGActive/activity_int5.B.out

echo "Testing TestCases/Activity/argumentArrayIndex3.B, TestResults/ICFGActive/argumentArrayIndex3.B.out Tested by PLM 05/02/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/argumentArrayIndex3.B > t
diff t TestResults/ICFGActive/argumentArrayIndex3.B.out

echo "Testing TestCases/Activity/activity_proc_call1.B, TestResults/ICFGActive/activity_proc_call1.B.out Tested by PLM 04/02/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/activity_proc_call1.B > t
diff t TestResults/ICFGActive/activity_proc_call1.B.out

echo "Testing TestCases/Activity/simple_if2.B, TestResults/ICFGActive/simple_if2.B.out Tested by PLM 04/02/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/simple_if2.B > t
diff t TestResults/ICFGActive/simple_if2.B.out

echo "Testing TestCases/Activity/sideEffect_3.B, TestResults/ICFGActive/sideEffect_3.B.out Tested by PLM 04/02/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/sideEffect_3.B > t
diff t TestResults/ICFGActive/sideEffect_3.B.out

echo "Testing TestCases/Activity/multiple_calls1.B, TestResults/ICFGActive/multiple_calls1.B.out Tested by PLM 04/02/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/multiple_calls1.B > t
diff t TestResults/ICFGActive/multiple_calls1.B.out

echo "Testing TestCases/Activity/multiple_calls2.B, TestResults/ICFGActive/multiple_calls2.B.out Tested by PLM 04/02/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/multiple_calls2.B > t
diff t TestResults/ICFGActive/multiple_calls2.B.out

echo "Testing TestCases/Activity/multiple_calls3.B, TestResults/ICFGActive/multiple_calls3.B.out Tested by MMS 08/04/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/multiple_calls3.B > t
diff t TestResults/ICFGActive/multiple_calls3.B.out

echo "Testing TestCases/Activity/multiple_calls4.B, TestResults/ICFGActive/multiple_calls4.B.out Tested by MMS 08/04/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/multiple_calls4.B > t
diff t TestResults/ICFGActive/multiple_calls4.B.out

echo "Testing TestCases/Activity/actualAsExpression.B, TestResults/ICFGActive/actualAsExpression.B.out Tested by PLM 05/17/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/actualAsExpression.B > t
diff t TestResults/ICFGActive/actualAsExpression.B.out

