echo "Testing TestCases/ReachDefs/ReachDefsConditional.B, TestResults/ReachDefs/ReachDefsConditional.B.out Checked by PLM 05/04/08"
./test-open64 --oa-ReachDefs TestCases/ReachDefs/ReachDefsConditional.B > t
diff t TestResults/ReachDefs/ReachDefsConditional.B.out

echo "Testing TestCases/ReachDefs/ReachDefsInterProcedural1.B, TestResults/ReachDefs/ReachDefsInterProcedural1.B.out Checked by PLM 05/04/08"
./test-open64 --oa-ReachDefs TestCases/ReachDefs/ReachDefsInterProcedural1.B > t
diff t TestResults/ReachDefs/ReachDefsInterProcedural1.B.out

echo "Testing TestCases/ReachDefs/ReachDefsNestedGlobals.B, TestResults/ReachDefs/ReachDefsNestedGlobals.B.out Checked by PLM 05/04/08"
./test-open64 --oa-ReachDefs TestCases/ReachDefs/ReachDefsNestedGlobals.B > t
diff t TestResults/ReachDefs/ReachDefsNestedGlobals.B.out

echo "Testing TestCases/ReachDefs/ReachDefsIndirect1.B, TestResults/ReachDefs/ReachDefsIndirect1.B.out Checked by PLM 05/04/08"
./test-open64 --oa-ReachDefs TestCases/ReachDefs/ReachDefsIndirect1.B > t
diff t TestResults/ReachDefs/ReachDefsIndirect1.B.out

echo "Testing TestCases/ReachDefs/ReachDefsInterProcedural2.B, TestResults/ReachDefs/ReachDefsInterProcedural2.B.out Checked by PLM 05/04/08"
./test-open64 --oa-ReachDefs TestCases/ReachDefs/ReachDefsInterProcedural2.B > t
diff t TestResults/ReachDefs/ReachDefsInterProcedural2.B.out

echo "Testing TestCases/ReachDefs/ReachDefsIndirect2.B, TestResults/ReachDefs/ReachDefsIndirect2.B.out Checked by PLM 05/04/08"
./test-open64 --oa-ReachDefs TestCases/ReachDefs/ReachDefsIndirect2.B > t
diff t TestResults/ReachDefs/ReachDefsIndirect2.B.out

echo "Testing TestCases/ReachDefs/ReachDefsPointer.B, TestResults/ReachDefs/ReachDefsPointer.B.out Checked by PLM 05/04/08"
./test-open64 --oa-ReachDefs TestCases/ReachDefs/ReachDefsPointer.B > t
diff t TestResults/ReachDefs/ReachDefsPointer.B.out

echo "Testing TestCases/ReachDefs/ReachDefsLoop.B, TestResults/ReachDefs/ReachDefsLoop.B.out Chekced by PLM 05/04/08"
./test-open64 --oa-ReachDefs TestCases/ReachDefs/ReachDefsLoop.B > t
diff t TestResults/ReachDefs/ReachDefsLoop.B.out

