echo "Testing TestCases/ReachDefs/reachdef_if1.B, TestResults/ReachDefs/reachdef_if1.B.out Checked by PLM 07/24/06"
./test-open64 --oa-ReachDefs TestCases/ReachDefs/reachdef_if1.B > t
diff t TestResults/ReachDefs/reachdef_if1.B.out

echo "Testing TestCases/ReachDefs/reachdef_if2.B, TestResults/ReachDefs/reachdef_if2.B.out Checked by PLM 07/24/06"
./test-open64 --oa-ReachDefs TestCases/ReachDefs/reachdef_if2.B > t
diff t TestResults/ReachDefs/reachdef_if2.B.out

echo "Testing TestCases/ReachDefs/reachdef_loopif1.B, TestResults/ReachDefs/reachdef_loopif1.B.out Checked by PLM 07/24/06"
./test-open64 --oa-ReachDefs TestCases/ReachDefs/reachdef_loopif1.B > t
diff t TestResults/ReachDefs/reachdef_loopif1.B.out

