echo "Testing TestCases/Alias/interalias_proc_call1.B, TestResults/AliasMapXAIF/interalias_proc_call1.B.out "
./test-open64 --oa-AliasMapXAIFFIAlias TestCases/Alias/interalias_proc_call1.B > t
diff t TestResults/AliasMapXAIF/interalias_proc_call1.B.out

echo "Testing TestCases/Alias/interalias_proc_call2.B, TestResults/AliasMapXAIF/interalias_proc_call2.B.out "
./test-open64 --oa-AliasMapXAIFFIAlias TestCases/Alias/interalias_proc_call2.B > t
diff t TestResults/AliasMapXAIF/interalias_proc_call2.B.out

echo "Testing TestCases/Alias/interalias_proc_call3.B, TestResults/AliasMapXAIF/interalias_proc_call3.B.out "
./test-open64 --oa-AliasMapXAIFFIAlias TestCases/Alias/interalias_proc_call3.B > t
diff t TestResults/AliasMapXAIF/interalias_proc_call3.B.out

echo "Testing TestCases/Alias/arrays5.B, TestResults/AliasMapXAIF/arrays5.B.out "
./test-open64 --oa-AliasMapXAIFFIAlias TestCases/Alias/arrays5.B > t
diff t TestResults/AliasMapXAIF/arrays5.B.out

