C
      SUBROUTINE VMLIQ (FL,T,LIQRES)
C     *********************
C
C         CALCULATES MOLAL VOLUME (CU FT/LB MOL) OF STREAM WITH MOLAL
C              FLOWS, FL, AS SATURATED LIQUID AT T DEG FAHR.
C
C         WRITTEN BY R.R.HUGHES         EES IDENT SP/VML
C              LAST REVISION AUGUST 27, 1973
C
      COMMON /UNPT/ JOUT,KNTRL,KFLAG,NCP,NPTP,NCST,NREC,NEN,WTEN(5),
     1  WEN(5,12),PTPEN(5,6),COST(5),EN(100),KTLN(15)
c     COMMON /ACT/ WTEN(5),WEN(5,12),PTPEN(5,6),COST(5),EN(100)
c     COMMON /UNACT/ JOUT,KNTRL,KFLAG,NPTP,NCST,NREC,NEN,NCP,KTLN(15)
      COMMON /QP/ CSXX(12,28),ANAMC(12,6)
      DIMENSION FL(12)
C+++++++++++++++++++++++++++++++++++++++++++++++++
	REAL LIQRES,SUM
C
        TS  = T/1000.
        SUM = 0.
        LIQRES= 0.
C
      DO 100 I = 1,NCP
C               LIQUID DENSITY CORRELATION
          DLI = AMAX1(1.0,(CSXX(I,16)+TS*(CSXX(I,17)+ TS*CSXX(I,18))))
        LIQRES= LIQRES+ CSXX(I,6)*FL(I)/DLI
100     SUM = SUM + FL(I)
	LIQRES= LIQRES/ SUM
C
      RETURN
      END
