echo "Generating TestResults/AliasMapFIAlias/interalias_proc_call1.B.out"
./test-open64 --oa-AliasMapFIAlias TestCases/Alias/interalias_proc_call1.B > TestResults/AliasMapFIAlias/interalias_proc_call1.B.out
echo "Generating TestResults/AliasMapFIAlias/interalias_proc_call2.B.out"
./test-open64 --oa-AliasMapFIAlias TestCases/Alias/interalias_proc_call2.B > TestResults/AliasMapFIAlias/interalias_proc_call2.B.out
echo "Generating TestResults/AliasMapFIAlias/interalias_proc_call3.B.out"
./test-open64 --oa-AliasMapFIAlias TestCases/Alias/interalias_proc_call3.B > TestResults/AliasMapFIAlias/interalias_proc_call3.B.out
echo "Generating TestResults/AliasMapFIAlias/activity_int4ai.B.out"
./test-open64 --oa-AliasMapFIAlias TestCases/Alias/activity_int4ai.B > TestResults/AliasMapFIAlias/activity_int4ai.B.out
echo "Generating TestResults/AliasMapFIAlias/interalias_proc_call5.B.out"
./test-open64 --oa-AliasMapFIAlias TestCases/Alias/interalias_proc_call5.B > TestResults/AliasMapFIAlias/interalias_proc_call5.B.out
echo "Generating TestResults/AliasMapFIAlias/interalias_proc_call4.B.out"
./test-open64 --oa-AliasMapFIAlias TestCases/Alias/interalias_proc_call4.B > TestResults/AliasMapFIAlias/interalias_proc_call4.B.out
