echo "Generating TestResults/CallGraph/activity_proc_call1.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/activity_proc_call1.B > TestResults/CallGraph/activity_proc_call1.B.out
echo "Generating TestResults/CallGraph/boxmodel-small.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/boxmodel-small.B > TestResults/CallGraph/boxmodel-small.B.out
echo "Generating TestResults/CallGraph/functions2.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/functions2.B > TestResults/CallGraph/functions2.B.out
echo "Generating TestResults/CallGraph/functions3.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/functions3.B > TestResults/CallGraph/functions3.B.out
echo "Generating TestResults/CallGraph/functions4.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/functions4.B > TestResults/CallGraph/functions4.B.out
echo "Generating TestResults/CallGraph/functions5.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/functions5.B > TestResults/CallGraph/functions5.B.out
echo "Generating TestResults/CallGraph/functions6.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/functions6.B > TestResults/CallGraph/functions6.B.out
echo "Generating TestResults/CallGraph/interalias_proc_call1.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/interalias_proc_call1.B > TestResults/CallGraph/interalias_proc_call1.B.out
echo "Generating TestResults/CallGraph/nested_calls_1.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/nested_calls_1.B > TestResults/CallGraph/nested_calls_1.B.out
echo "Generating TestResults/CallGraph/If_Loop4.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/If_Loop4.B > TestResults/CallGraph/If_Loop4.B.out
echo "Generating TestResults/CallGraph/passiveStatement.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/passiveStatement.B > TestResults/CallGraph/passiveStatement.B.out
echo "Generating TestResults/CallGraph/simple1.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/simple1.B > TestResults/CallGraph/simple1.B.out
echo "Generating TestResults/CallGraph/If_Loop5.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/If_Loop5.B > TestResults/CallGraph/If_Loop5.B.out
echo "Generating TestResults/CallGraph/simple2.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/simple2.B > TestResults/CallGraph/simple2.B.out
echo "Generating TestResults/CallGraph/simple3.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/simple3.B > TestResults/CallGraph/simple3.B.out
echo "Generating TestResults/CallGraph/float_intrinsic.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/float_intrinsic.B > TestResults/CallGraph/float_intrinsic.B.out
echo "Generating TestResults/CallGraph/lion.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/lion.B > TestResults/CallGraph/lion.B.out
echo "Generating TestResults/CallGraph/tanh_f_arg.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/tanh_f_arg.B > TestResults/CallGraph/tanh_f_arg.B.out
echo "Generating TestResults/CallGraph/nested_calls_1.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/nested_calls_1.B > TestResults/CallGraph/nested_calls_1.B.out
echo "Generating TestResults/CallGraph/bat.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/bat.B > TestResults/CallGraph/bat.B.out
echo "Generating TestResults/CallGraph/nested_calls_3.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/nested_calls_3.B > TestResults/CallGraph/nested_calls_3.B.out
echo "Generating TestResults/CallGraph/cast1.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/cast1.B > TestResults/CallGraph/cast1.B.out
echo "Generating TestResults/CallGraph/nested_calls_4.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/nested_calls_4.B > TestResults/CallGraph/nested_calls_4.B.out
echo "Generating TestResults/CallGraph/constPrec.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/constPrec.B > TestResults/CallGraph/constPrec.B.out
echo "Generating TestResults/CallGraph/readWrite1.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/readWrite1.B > TestResults/CallGraph/readWrite1.B.out
echo "Generating TestResults/CallGraph/funcCallAsActual.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/funcCallAsActual.B > TestResults/CallGraph/funcCallAsActual.B.out
echo "Generating TestResults/CallGraph/functions2_stub.B.out"
./test-open64 --oa-CallGraph TestCases/CallGraph/functions2_stub.B > TestResults/CallGraph/functions2_stub.B.out
