echo "Generating TestResults/ReachDefs/reachdef_if1.B.out"
./test-open64 --oa-ReachDefs TestCases/ReachDefs/reachdef_if1.B > TestResults/ReachDefs/reachdef_if1.B.out
echo "Generating TestResults/ReachDefs/reachdef_if2.B.out"
./test-open64 --oa-ReachDefs TestCases/ReachDefs/reachdef_if2.B > TestResults/ReachDefs/reachdef_if2.B.out
echo "Generating TestResults/ReachDefs/reachdef_loopif1.B.out"
./test-open64 --oa-ReachDefs TestCases/ReachDefs/reachdef_loopif1.B > TestResults/ReachDefs/reachdef_loopif1.B.out
