echo "Testing TestCases/Alias/interalias_proc_call1.B, TestResults/AliasIRInterface/interalias_proc_call1.B.out checked by MMS 4/27/06"
./FORTRANtoOA TestCases/Alias/interalias_proc_call1.B > t
diff t TestResults/AliasIRInterface/interalias_proc_call1.B.out

echo "Testing TestCases/Alias/interalias_proc_call2.B, TestResults/AliasIRInterface/interalias_proc_call2.B.out checked by MMS 4/27/06"
./FORTRANtoOA TestCases/Alias/interalias_proc_call2.B > t
diff t TestResults/AliasIRInterface/interalias_proc_call2.B.out

echo "Testing TestCases/Alias/interalias_proc_call3.B, TestResults/AliasIRInterface/interalias_proc_call3.B.out checked by MMS 5/8/06"
./FORTRANtoOA TestCases/Alias/interalias_proc_call3.B > t
diff t TestResults/AliasIRInterface/interalias_proc_call3.B.out

echo "Testing TestCases/Alias/interalias_proc_call4.B, TestResults/AliasIRInterface/interalias_proc_call4.B.out checked by MMS 5/17/06"
./FORTRANtoOA TestCases/Alias/interalias_proc_call4.B > t
diff t TestResults/AliasIRInterface/interalias_proc_call4.B.out

echo "Testing TestCases/Alias/arrays5.B, TestResults/AliasIRInterface/arrays5.B.out checked by MMS 4/28/06"
./FORTRANtoOA TestCases/Alias/arrays5.B > t
diff t TestResults/AliasIRInterface/arrays5.B.out

echo "Testing TestCases/Alias/functions1.B, TestResults/AliasIRInterface/functions1.B.out checked by MMS 4/28/06"
./FORTRANtoOA TestCases/Alias/functions1.B > t
diff t TestResults/AliasIRInterface/functions1.B.out

echo "Testing TestCases/Alias/globalActive_2.B, TestResults/AliasIRInterface/globalActive_2.B.out checked by MMS 5/8/06"
./FORTRANtoOA TestCases/Alias/globalActive_2.B > t
diff t TestResults/AliasIRInterface/globalActive_2.B.out

