echo "Generating TestResults/AliasTagCSFIAlias/conditional.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagCSFIAlias/conditional.f
mv conditional.B TestCases/AliasTagCSFIAlias/conditional.B
./test-open64 --oa-AliasTagCSFIAlias TestCases/AliasTagCSFIAlias/conditional.B > TestResults/AliasTagCSFIAlias/conditional.B.out
echo "Generating TestResults/AliasTagCSFIAlias/multiple_calls3.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagCSFIAlias/multiple_calls3.f
mv multiple_calls3.B TestCases/AliasTagCSFIAlias/multiple_calls3.B
./test-open64 --oa-AliasTagCSFIAlias TestCases/AliasTagCSFIAlias/multiple_calls3.B > TestResults/AliasTagCSFIAlias/multiple_calls3.B.out
