echo "Generating TestResults/AliasMapXAIF/Alias_Pointer.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/Alias_Pointer.f
mv Alias_Pointer.B TestCases/AliasMapXAIF/Alias_Pointer.B
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/Alias_Pointer.B > TestResults/AliasMapXAIF/Alias_Pointer.B.out
echo "Generating TestResults/AliasMapXAIF/NoAlias_StructVar.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/NoAlias_StructVar.f
mv NoAlias_StructVar.B TestCases/AliasMapXAIF/NoAlias_StructVar.B
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_StructVar.B > TestResults/AliasMapXAIF/NoAlias_StructVar.B.out
echo "Generating TestResults/AliasMapXAIF/NoAlias_Named.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/NoAlias_Named.f
mv NoAlias_Named.B TestCases/AliasMapXAIF/NoAlias_Named.B
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_Named.B > TestResults/AliasMapXAIF/NoAlias_Named.B.out
echo "Generating TestResults/AliasMapXAIF/NoAlias_Unnamed.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/NoAlias_Unnamed.f
mv NoAlias_Unnamed.B TestCases/AliasMapXAIF/NoAlias_Unnamed.B
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_Unnamed.B > TestResults/AliasMapXAIF/NoAlias_Unnamed.B.out
echo "Generating TestResults/AliasMapXAIF/NoAlias_FieldAccess.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/NoAlias_FieldAccess.f
mv NoAlias_FieldAccess.B TestCases/AliasMapXAIF/NoAlias_FieldAccess.B
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_FieldAccess.B > TestResults/AliasMapXAIF/NoAlias_FieldAccess.B.out
echo "Generating TestResults/AliasMapXAIF/NoAlias_SubSet.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/NoAlias_SubSet.f
mv NoAlias_SubSet.B TestCases/AliasMapXAIF/NoAlias_SubSet.B
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/NoAlias_SubSet.B > TestResults/AliasMapXAIF/NoAlias_SubSet.B.out
echo "Generating TestResults/AliasMapXAIF/Param_Alias.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/Param_Alias.f
mv Param_Alias.B TestCases/AliasMapXAIF/Param_Alias.B
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/Param_Alias.B > TestResults/AliasMapXAIF/Param_Alias.B.out
echo "Generating TestResults/AliasMapXAIF/multiple_calls.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/multiple_calls.f
mv multiple_calls.B TestCases/AliasMapXAIF/multiple_calls.B
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/multiple_calls.B > TestResults/AliasMapXAIF/multiple_calls.B.out
echo "Generating TestResults/AliasMapXAIF/pointer_to_local.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasMapXAIF/pointer_to_local.f
mv pointer_to_local.B TestCases/AliasMapXAIF/pointer_to_local.B
./test-open64 --oa-AliasMapXAIF TestCases/AliasMapXAIF/pointer_to_local.B > TestResults/AliasMapXAIF/pointer_to_local.B.out
