echo "Generating TestResults/CSFIActive/activity_int5.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/activity_int5.f
mv activity_int5.B TestCases/Activity/activity_int5.B
./test-open64 --oa-CSFIActivity TestCases/Activity/activity_int5.B > TestResults/CSFIActive/activity_int5.B.out
echo "Generating TestResults/CSFIActive/argumentArrayIndex3.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/argumentArrayIndex3.f
mv argumentArrayIndex3.B TestCases/Activity/argumentArrayIndex3.B
./test-open64 --oa-CSFIActivity TestCases/Activity/argumentArrayIndex3.B > TestResults/CSFIActive/argumentArrayIndex3.B.out
echo "Generating TestResults/CSFIActive/activity_proc_call1.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/activity_proc_call1.f
mv activity_proc_call1.B TestCases/Activity/activity_proc_call1.B
./test-open64 --oa-CSFIActivity TestCases/Activity/activity_proc_call1.B > TestResults/CSFIActive/activity_proc_call1.B.out
echo "Generating TestResults/CSFIActive/simple_if2.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/simple_if2.f
mv simple_if2.B TestCases/Activity/simple_if2.B
./test-open64 --oa-CSFIActivity TestCases/Activity/simple_if2.B > TestResults/CSFIActive/simple_if2.B.out
echo "Generating TestResults/CSFIActive/sideEffect_3.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/sideEffect_3.f
mv sideEffect_3.B TestCases/Activity/sideEffect_3.B
./test-open64 --oa-CSFIActivity TestCases/Activity/sideEffect_3.B > TestResults/CSFIActive/sideEffect_3.B.out
echo "Generating TestResults/CSFIActive/multiple_calls1.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/multiple_calls1.f
mv multiple_calls1.B TestCases/Activity/multiple_calls1.B
./test-open64 --oa-CSFIActivity TestCases/Activity/multiple_calls1.B > TestResults/CSFIActive/multiple_calls1.B.out
echo "Generating TestResults/CSFIActive/multiple_calls2.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/multiple_calls2.f
mv multiple_calls2.B TestCases/Activity/multiple_calls2.B
./test-open64 --oa-CSFIActivity TestCases/Activity/multiple_calls2.B > TestResults/CSFIActive/multiple_calls2.B.out
echo "Generating TestResults/CSFIActive/actualAsExpression.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/actualAsExpression.f
mv actualAsExpression.B TestCases/Activity/actualAsExpression.B
./test-open64 --oa-CSFIActivity TestCases/Activity/actualAsExpression.B > TestResults/CSFIActive/actualAsExpression.B.out
