echo "Generating TestResults/ParamBindings/functions2.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/functions2.B > TestResults/ParamBindings/functions2.B.out
echo "Generating TestResults/ParamBindings/functions6.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/functions6.B > TestResults/ParamBindings/functions6.B.out
echo "Generating TestResults/ParamBindings/functions3.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/functions3.B > TestResults/ParamBindings/functions3.B.out
echo "Generating TestResults/ParamBindings/interalias_proc_call1.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/interalias_proc_call1.B > TestResults/ParamBindings/interalias_proc_call1.B.out
echo "Generating TestResults/ParamBindings/nested_calls_1.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/nested_calls_1.B > TestResults/ParamBindings/nested_calls_1.B.out
echo "Generating TestResults/ParamBindings/divide.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/divide.B > TestResults/ParamBindings/divide.B.out
echo "Generating TestResults/ParamBindings/solve.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/solve.B > TestResults/ParamBindings/solve.B.out
echo "Generating TestResults/ParamBindings/Matrix_bits.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/Matrix_bits.B > TestResults/ParamBindings/Matrix_bits.B.out
echo "Generating TestResults/ParamBindings/stat_selection.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/stat_selection.B > TestResults/ParamBindings/stat_selection.B.out
echo "Generating TestResults/ParamBindings/GCD.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/GCD.B > TestResults/ParamBindings/GCD.B.out
echo "Generating TestResults/ParamBindings/ETOX.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/ETOX.B > TestResults/ParamBindings/ETOX.B.out
echo "Generating TestResults/ParamBindings/swap.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/swap.B > TestResults/ParamBindings/swap.B.out
echo "Generating TestResults/ParamBindings/readin.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/readin.B > TestResults/ParamBindings/readin.B.out
echo "Generating TestResults/ParamBindings/array.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/array.B > TestResults/ParamBindings/array.B.out
echo "Generating TestResults/ParamBindings/area_circle.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/area_circle.B > TestResults/ParamBindings/area_circle.B.out
echo "Generating TestResults/ParamBindings/subroutine.B.out"
./test-open64 --oa-ParamBindings TestCases/ParamBindings/subroutine.B > TestResults/ParamBindings/subroutine.B.out
