echo "Generating TestResults/ParamBindings/keyword_arguments.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/ParamBindings/keyword_arguments.f
mv keyword_arguments.B TestCases/ParamBindings/keyword_arguments.B
./test-open64 --oa-ParamBindings TestCases/ParamBindings/keyword_arguments.B > TestResults/ParamBindings/keyword_arguments.B.out
echo "Generating TestResults/ParamBindings/optional_param.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/ParamBindings/optional_param.f90
mv optional_param.B TestCases/ParamBindings/optional_param.B
./test-open64 --oa-ParamBindings TestCases/ParamBindings/optional_param.B > TestResults/ParamBindings/optional_param.B.out
echo "Generating TestResults/ParamBindings/param_expressions.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/ParamBindings/param_expressions.f
mv param_expressions.B TestCases/ParamBindings/param_expressions.B
./test-open64 --oa-ParamBindings TestCases/ParamBindings/param_expressions.B > TestResults/ParamBindings/param_expressions.B.out
echo "Generating TestResults/ParamBindings/recursion.B.out"
${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/ParamBindings/recursion.f90
mv recursion.B TestCases/ParamBindings/recursion.B
./test-open64 --oa-ParamBindings TestCases/ParamBindings/recursion.B > TestResults/ParamBindings/recursion.B.out
