echo "Generating TestResults/UDDUChainsTests/reachdef_if1.B.out"
./test-open64 --oa-UDDUChains TestCases/UDDUChainsTests/reachdef_if1.B > TestResults/UDDUChainsTests/reachdef_if1.B.out
echo "Generating TestResults/UDDUChainsTests/reachdef_if2.B.out"
./test-open64 --oa-UDDUChains TestCases/UDDUChainsTests/reachdef_if2.B > TestResults/UDDUChainsTests/reachdef_if2.B.out
echo "Generating TestResults/UDDUChainsTests/reachdef_loopif1.B.out"
./test-open64 --oa-UDDUChains TestCases/UDDUChainsTests/reachdef_loopif1.B > TestResults/UDDUChainsTests/reachdef_loopif1.B.out
echo "Generating TestResults/UDDUChainsTests/Loop_simple_10.B.out"
./test-open64 --oa-UDDUChains TestCases/UDDUChainsTests/Loop_simple_10.B > TestResults/UDDUChainsTests/Loop_simple_10.B.out
