${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagFIAlias/pointer.f
mv pointer.B TestCases/AliasTagFIAlias/pointer.B
echo "Testing TestCases/AliasTagFIAlias/pointer.B, TestResults/AliasTagFIAlias/pointer.B.out Checked by MMS 04/22/08"
./test-open64 --oa-AliasTagFIAlias TestCases/AliasTagFIAlias/pointer.B > t
diff -I "LOC 0 0 source files" t TestResults/AliasTagFIAlias/pointer.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagFIAlias/conditional.f
mv conditional.B TestCases/AliasTagFIAlias/conditional.B
echo "Testing TestCases/AliasTagFIAlias/conditional.B, TestResults/AliasTagFIAlias/conditional.B.out Checked by MMS 04/22/08"
./test-open64 --oa-AliasTagFIAlias TestCases/AliasTagFIAlias/conditional.B > t
diff -I "LOC 0 0 source files" t TestResults/AliasTagFIAlias/conditional.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagFIAlias/interalias_proc_call1.f
mv interalias_proc_call1.B TestCases/AliasTagFIAlias/interalias_proc_call1.B
echo "Testing TestCases/AliasTagFIAlias/interalias_proc_call1.B, TestResults/AliasTagFIAlias/interalias_proc_call1.B.out Checked by MMS 04/22/08"
./test-open64 --oa-AliasTagFIAlias TestCases/AliasTagFIAlias/interalias_proc_call1.B > t
diff -I "LOC 0 0 source files" t TestResults/AliasTagFIAlias/interalias_proc_call1.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagFIAlias/interalias_proc_call6.f
mv interalias_proc_call6.B TestCases/AliasTagFIAlias/interalias_proc_call6.B
echo "Testing TestCases/AliasTagFIAlias/interalias_proc_call6.B, TestResults/AliasTagFIAlias/interalias_proc_call6.B.out Checked by MMS 04/22/08"
./test-open64 --oa-AliasTagFIAlias TestCases/AliasTagFIAlias/interalias_proc_call6.B > t
diff -I "LOC 0 0 source files" t TestResults/AliasTagFIAlias/interalias_proc_call6.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagFIAlias/interalias_proc_call5.f
mv interalias_proc_call5.B TestCases/AliasTagFIAlias/interalias_proc_call5.B
echo "Testing TestCases/AliasTagFIAlias/interalias_proc_call5.B, TestResults/AliasTagFIAlias/interalias_proc_call5.B.out Checked by PLM 02/23/08"
./test-open64 --oa-AliasTagFIAlias TestCases/AliasTagFIAlias/interalias_proc_call5.B > t
diff -I "LOC 0 0 source files" t TestResults/AliasTagFIAlias/interalias_proc_call5.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagFIAlias/Unnamed_alias.f
mv Unnamed_alias.B TestCases/AliasTagFIAlias/Unnamed_alias.B
echo "Testing TestCases/AliasTagFIAlias/Unnamed_alias.B, TestResults/AliasTagFIAlias/Unnamed_alias.B.out Checked by PLM 02/22/08"
./test-open64 --oa-AliasTagFIAlias TestCases/AliasTagFIAlias/Unnamed_alias.B > t
diff -I "LOC 0 0 source files" t TestResults/AliasTagFIAlias/Unnamed_alias.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagFIAlias/Jean.f90
mv Jean.B TestCases/AliasTagFIAlias/Jean.B
echo "Testing TestCases/AliasTagFIAlias/Jean.B, TestResults/AliasTagFIAlias/Jean.B.out Checked by PLM 02/23/08"
./test-open64 --oa-AliasTagFIAlias TestCases/AliasTagFIAlias/Jean.B > t
diff -I "LOC 0 0 source files" t TestResults/AliasTagFIAlias/Jean.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagFIAlias/interalias_proc_call7.f
mv interalias_proc_call7.B TestCases/AliasTagFIAlias/interalias_proc_call7.B
echo "Testing TestCases/AliasTagFIAlias/interalias_proc_call7.B, TestResults/AliasTagFIAlias/interalias_proc_call7.B.out Checked by PLM 02/23/08"
./test-open64 --oa-AliasTagFIAlias TestCases/AliasTagFIAlias/interalias_proc_call7.B > t
diff -I "LOC 0 0 source files" t TestResults/AliasTagFIAlias/interalias_proc_call7.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagFIAlias/struct_pointer1.f
mv struct_pointer1.B TestCases/AliasTagFIAlias/struct_pointer1.B
echo "Testing TestCases/AliasTagFIAlias/struct_pointer1.B, TestResults/AliasTagFIAlias/struct_pointer1.B.out Checked by PLM 02/22/08"
./test-open64 --oa-AliasTagFIAlias TestCases/AliasTagFIAlias/struct_pointer1.B > t
diff -I "LOC 0 0 source files" t TestResults/AliasTagFIAlias/struct_pointer1.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagFIAlias/struct_pointer2.f
mv struct_pointer2.B TestCases/AliasTagFIAlias/struct_pointer2.B
echo "Testing TestCases/AliasTagFIAlias/struct_pointer2.B, TestResults/AliasTagFIAlias/struct_pointer2.B.out Checked by PLM 02/22/08"
./test-open64 --oa-AliasTagFIAlias TestCases/AliasTagFIAlias/struct_pointer2.B > t
diff -I "LOC 0 0 source files" t TestResults/AliasTagFIAlias/struct_pointer2.B.out

