echo "Testing TestCases/Alias/interalias_proc_call1.B, TestResults/AliasIRInterface/interalias_proc_call1.B.out checked by MMS 09/28/07"
./FORTRANtoOA TestCases/Alias/interalias_proc_call1.B > t
diff t TestResults/AliasIRInterface/interalias_proc_call1.B.out

echo "Testing TestCases/Alias/interalias_proc_call2.B, TestResults/AliasIRInterface/interalias_proc_call2.B.out checked by MMS 09/28/07"
./FORTRANtoOA TestCases/Alias/interalias_proc_call2.B > t
diff t TestResults/AliasIRInterface/interalias_proc_call2.B.out

echo "Testing TestCases/Alias/interalias_proc_call3.B, TestResults/AliasIRInterface/interalias_proc_call3.B.out checked by MMS 09/28/07"
./FORTRANtoOA TestCases/Alias/interalias_proc_call3.B > t
diff t TestResults/AliasIRInterface/interalias_proc_call3.B.out

echo "Testing TestCases/Alias/interalias_proc_call4.B, TestResults/AliasIRInterface/interalias_proc_call4.B.out checked by MMS 09/28/07"
./FORTRANtoOA TestCases/Alias/interalias_proc_call4.B > t
diff t TestResults/AliasIRInterface/interalias_proc_call4.B.out

echo "Testing TestCases/Alias/arrays5.B, TestResults/AliasIRInterface/arrays5.B.out checked by MMS 09/28/07"
./FORTRANtoOA TestCases/Alias/arrays5.B > t
diff t TestResults/AliasIRInterface/arrays5.B.out

echo "Testing TestCases/Alias/functions1.B, TestResults/AliasIRInterface/functions1.B.out checked by MMS 09/28/07"
./FORTRANtoOA TestCases/Alias/functions1.B > t
diff t TestResults/AliasIRInterface/functions1.B.out

echo "Testing TestCases/Alias/globalActive_2.B, TestResults/AliasIRInterface/globalActive_2.B.out checked by MMS 09/28/07"
./FORTRANtoOA TestCases/Alias/globalActive_2.B > t
diff t TestResults/AliasIRInterface/globalActive_2.B.out

echo "Testing TestCases/Alias/formalarrayactual.B, TestResults/AliasIRInterface/formalarrayactual.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactual.B > t
diff t TestResults/AliasIRInterface/formalarrayactual.B.out

echo "Testing TestCases/Alias/formalarrayactualin.B, TestResults/AliasIRInterface/formalarrayactualin.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualin.B > t
diff t TestResults/AliasIRInterface/formalarrayactualin.B.out

echo "Testing TestCases/Alias/formalarrayactualout.B, TestResults/AliasIRInterface/formalarrayactualout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualout.B > t
diff t TestResults/AliasIRInterface/formalarrayactualout.B.out

echo "Testing TestCases/Alias/formalarrayactualinout.B, TestResults/AliasIRInterface/formalarrayactualinout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualinout.B > t
diff t TestResults/AliasIRInterface/formalarrayactualinout.B.out

echo "Testing TestCases/Alias/formalarrayactualsubscript.B, TestResults/AliasIRInterface/formalarrayactualsubscript.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualsubscript.B > t
diff t TestResults/AliasIRInterface/formalarrayactualsubscript.B.out

echo "Testing TestCases/Alias/formalarrayactualsubscriptin.B, TestResults/AliasIRInterface/formalarrayactualsubscriptin.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualsubscriptin.B > t
diff t TestResults/AliasIRInterface/formalarrayactualsubscriptin.B.out

echo "Testing TestCases/Alias/formalarrayactualsubscriptout.B, TestResults/AliasIRInterface/formalarrayactualsubscriptout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualsubscriptout.B > t
diff t TestResults/AliasIRInterface/formalarrayactualsubscriptout.B.out

echo "Testing TestCases/Alias/formalarrayactualsubscriptinout.B, TestResults/AliasIRInterface/formalarrayactualsubscriptinout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualsubscriptinout.B > t
diff t TestResults/AliasIRInterface/formalarrayactualsubscriptinout.B.out

echo "Testing TestCases/Alias/localarrayactual.B, TestResults/AliasIRInterface/localarrayactual.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localarrayactual.B > t
diff t TestResults/AliasIRInterface/localarrayactual.B.out

echo "Testing TestCases/Alias/localscalaractual.B, TestResults/AliasIRInterface/localscalaractual.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localscalaractual.B > t
diff t TestResults/AliasIRInterface/localscalaractual.B.out

echo "Testing TestCases/Alias/formalarrayofarrayuse.B, TestResults/AliasIRInterface/formalarrayofarrayuse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayofarrayuse.B > t
diff t TestResults/AliasIRInterface/formalarrayofarrayuse.B.out

echo "Testing TestCases/Alias/formalarrayofarrayusesubscript.B, TestResults/AliasIRInterface/formalarrayofarrayusesubscript.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayofarrayusesubscript.B > t
diff t TestResults/AliasIRInterface/formalarrayofarrayusesubscript.B.out

echo "Testing TestCases/Alias/formalarrayofarraydef.B, TestResults/AliasIRInterface/formalarrayofarraydef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayofarraydef.B > t
diff t TestResults/AliasIRInterface/formalarrayofarraydef.B.out

echo "Testing TestCases/Alias/localarrayofarrayuse.B, TestResults/AliasIRInterface/localarrayofarrayuse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localarrayofarrayuse.B > t
diff t TestResults/AliasIRInterface/localarrayofarrayuse.B.out

echo "Testing TestCases/Alias/localarrayofarrayusesubscript.B, TestResults/AliasIRInterface/localarrayofarrayusesubscript.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localarrayofarrayusesubscript.B > t
diff t TestResults/AliasIRInterface/localarrayofarrayusesubscript.B.out

echo "Testing TestCases/Alias/localarrayofarraydef.B, TestResults/AliasIRInterface/localarrayofarraydef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localarrayofarraydef.B > t
diff t TestResults/AliasIRInterface/localarrayofarraydef.B.out

echo "Testing TestCases/Alias/modulearrayusewholearray.B, TestResults/AliasIRInterface/modulearrayusewholearray.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/modulearrayusewholearray.B > t
diff t TestResults/AliasIRInterface/modulearrayusewholearray.B.out

echo "Testing TestCases/Alias/modulearrayuse.B, TestResults/AliasIRInterface/modulearrayuse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/modulearrayuse.B > t
diff t TestResults/AliasIRInterface/modulearrayuse.B.out

echo "Testing TestCases/Alias/modulearraysubscriptuse.B, TestResults/AliasIRInterface/modulearraysubscriptuse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/modulearraysubscriptuse.B > t
diff t TestResults/AliasIRInterface/modulearraysubscriptuse.B.out

echo "Testing TestCases/Alias/modulearraydefwholearray.B, TestResults/AliasIRInterface/modulearraydefwholearray.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/modulearraydefwholearray.B > t
diff t TestResults/AliasIRInterface/modulearraydefwholearray.B.out

echo "Testing TestCases/Alias/modulearraydef.B, TestResults/AliasIRInterface/modulearraydef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/modulearraydef.B > t
diff t TestResults/AliasIRInterface/modulearraydef.B.out

echo "Testing TestCases/Alias/modulearraysubscriptdef.B, TestResults/AliasIRInterface/modulearraysubscriptdef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/modulearraysubscriptdef.B > t
diff t TestResults/AliasIRInterface/modulearraysubscriptdef.B.out

echo "Testing TestCases/Alias/modulearraysectiondef.B, TestResults/AliasIRInterface/modulearraysectiondef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/modulearraysectiondef.B > t
diff t TestResults/AliasIRInterface/modulearraysectiondef.B.out

echo "Testing TestCases/Alias/modulescalaruse.B, TestResults/AliasIRInterface/modulescalaruse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/modulescalaruse.B > t
diff t TestResults/AliasIRInterface/modulescalaruse.B.out

echo "Testing TestCases/Alias/modulescalardef.B, TestResults/AliasIRInterface/modulescalardef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/modulescalardef.B > t
diff t TestResults/AliasIRInterface/modulescalardef.B.out

echo "Testing TestCases/Alias/globalarrayusewholearray.B, TestResults/AliasIRInterface/globalarrayusewholearray.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/globalarrayusewholearray.B > t
diff t TestResults/AliasIRInterface/globalarrayusewholearray.B.out

echo "Testing TestCases/Alias/globalarrayuse.B, TestResults/AliasIRInterface/globalarrayuse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/globalarrayuse.B > t
diff t TestResults/AliasIRInterface/globalarrayuse.B.out

echo "Testing TestCases/Alias/globalarrayusesubscript.B, TestResults/AliasIRInterface/globalarrayusesubscript.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/globalarrayusesubscript.B > t
diff t TestResults/AliasIRInterface/globalarrayusesubscript.B.out

echo "Testing TestCases/Alias/globalarraydefwholearray.B, TestResults/AliasIRInterface/globalarraydefwholearray.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/globalarraydefwholearray.B > t
diff t TestResults/AliasIRInterface/globalarraydefwholearray.B.out

echo "Testing TestCases/Alias/globalarraydef.B, TestResults/AliasIRInterface/globalarraydef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/globalarraydef.B > t
diff t TestResults/AliasIRInterface/globalarraydef.B.out

echo "Testing TestCases/Alias/globalarraydefsubscript.B, TestResults/AliasIRInterface/globalarraydefsubscript.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/globalarraydefsubscript.B > t
diff t TestResults/AliasIRInterface/globalarraydefsubscript.B.out

echo "Testing TestCases/Alias/globalarraysectiondef.B, TestResults/AliasIRInterface/globalarraysectiondef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/globalarraysectiondef.B > t
diff t TestResults/AliasIRInterface/globalarraysectiondef.B.out

echo "Testing TestCases/Alias/globalscalaruse.B, TestResults/AliasIRInterface/globalscalaruse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/globalscalaruse.B > t
diff t TestResults/AliasIRInterface/globalscalaruse.B.out

echo "Testing TestCases/Alias/globalscalardef.B, TestResults/AliasIRInterface/globalscalardef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/globalscalardef.B > t
diff t TestResults/AliasIRInterface/globalscalardef.B.out

echo "Testing TestCases/Alias/formalarrayusewholearray.B, TestResults/AliasIRInterface/formalarrayusewholearray.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayusewholearray.B > t
diff t TestResults/AliasIRInterface/formalarrayusewholearray.B.out

echo "Testing TestCases/Alias/formalarrayuse.B, TestResults/AliasIRInterface/formalarrayuse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayuse.B > t
diff t TestResults/AliasIRInterface/formalarrayuse.B.out

echo "Testing TestCases/Alias/formalarraysubscriptuse.B, TestResults/AliasIRInterface/formalarraysubscriptuse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarraysubscriptuse.B > t
diff t TestResults/AliasIRInterface/formalarraysubscriptuse.B.out

echo "Testing TestCases/Alias/formalarrayusein.B, TestResults/AliasIRInterface/formalarrayusein.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayusein.B > t
diff t TestResults/AliasIRInterface/formalarrayusein.B.out

echo "Testing TestCases/Alias/formalarrayuseout.B, TestResults/AliasIRInterface/formalarrayuseout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayuseout.B > t
diff t TestResults/AliasIRInterface/formalarrayuseout.B.out

echo "Testing TestCases/Alias/formalarrayuseinout.B, TestResults/AliasIRInterface/formalarrayuseinout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayuseinout.B > t
diff t TestResults/AliasIRInterface/formalarrayuseinout.B.out

echo "Testing TestCases/Alias/formalarraydefwholearray.B, TestResults/AliasIRInterface/formalarraydefwholearray.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarraydefwholearray.B > t
diff t TestResults/AliasIRInterface/formalarraydefwholearray.B.out

echo "Testing TestCases/Alias/formalarraydef.B, TestResults/AliasIRInterface/formalarraydef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarraydef.B > t
diff t TestResults/AliasIRInterface/formalarraydef.B.out

echo "Testing TestCases/Alias/formalarraysubscriptdef.B, TestResults/AliasIRInterface/formalarraysubscriptdef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarraysubscriptdef.B > t
diff t TestResults/AliasIRInterface/formalarraysubscriptdef.B.out

echo "Testing TestCases/Alias/formalarraysectiondef.B, TestResults/AliasIRInterface/formalarraysectiondef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarraysectiondef.B > t
diff t TestResults/AliasIRInterface/formalarraysectiondef.B.out

echo "Testing TestCases/Alias/formalarraydefout.B, TestResults/AliasIRInterface/formalarraydefout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarraydefout.B > t
diff t TestResults/AliasIRInterface/formalarraydefout.B.out

echo "Testing TestCases/Alias/formalarraydefinout.B, TestResults/AliasIRInterface/formalarraydefinout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarraydefinout.B > t
diff t TestResults/AliasIRInterface/formalarraydefinout.B.out

echo "Testing TestCases/Alias/formalscalaruse.B, TestResults/AliasIRInterface/formalscalaruse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalscalaruse.B > t
diff t TestResults/AliasIRInterface/formalscalaruse.B.out

echo "Testing TestCases/Alias/formalscalarusein.B, TestResults/AliasIRInterface/formalscalarusein.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalscalarusein.B > t
diff t TestResults/AliasIRInterface/formalscalarusein.B.out

echo "Testing TestCases/Alias/formalscalaruseout.B, TestResults/AliasIRInterface/formalscalaruseout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalscalaruseout.B > t
diff t TestResults/AliasIRInterface/formalscalaruseout.B.out

echo "Testing TestCases/Alias/formalscalaruseinout.B, TestResults/AliasIRInterface/formalscalaruseinout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalscalaruseinout.B > t
diff t TestResults/AliasIRInterface/formalscalaruseinout.B.out

echo "Testing TestCases/Alias/formalscalardef.B, TestResults/AliasIRInterface/formalscalardef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalscalardef.B > t
diff t TestResults/AliasIRInterface/formalscalardef.B.out

echo "Testing TestCases/Alias/formalscalardefout.B, TestResults/AliasIRInterface/formalscalardefout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalscalardefout.B > t
diff t TestResults/AliasIRInterface/formalscalardefout.B.out

echo "Testing TestCases/Alias/formalscalardefinout.B, TestResults/AliasIRInterface/formalscalardefinout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalscalardefinout.B > t
diff t TestResults/AliasIRInterface/formalscalardefinout.B.out

echo "Testing TestCases/Alias/localarrayuse.B, TestResults/AliasIRInterface/localarrayuse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localarrayuse.B > t
diff t TestResults/AliasIRInterface/localarrayuse.B.out

echo "Testing TestCases/Alias/localarraysubscriptuse.B, TestResults/AliasIRInterface/localarraysubscriptuse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localarraysubscriptuse.B > t
diff t TestResults/AliasIRInterface/localarraysubscriptuse.B.out

echo "Testing TestCases/Alias/localarraydef.B, TestResults/AliasIRInterface/localarraydef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localarraydef.B > t
diff t TestResults/AliasIRInterface/localarraydef.B.out

echo "Testing TestCases/Alias/localarraysubscriptdef.B, TestResults/AliasIRInterface/localarraysubscriptdef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localarraysubscriptdef.B > t
diff t TestResults/AliasIRInterface/localarraysubscriptdef.B.out

echo "Testing TestCases/Alias/localscalaruse.B, TestResults/AliasIRInterface/localscalaruse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localscalaruse.B > t
diff t TestResults/AliasIRInterface/localscalaruse.B.out

echo "Testing TestCases/Alias/localscalardef.B, TestResults/AliasIRInterface/localscalardef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localscalardef.B > t
diff t TestResults/AliasIRInterface/localscalardef.B.out

echo "Testing TestCases/Alias/formalarrayactualcalleeusewholearray.B, TestResults/AliasIRInterface/formalarrayactualcalleeusewholearray.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualcalleeusewholearray.B > t
diff t TestResults/AliasIRInterface/formalarrayactualcalleeusewholearray.B.out

echo "Testing TestCases/Alias/formalarrayactualcalleeuse.B, TestResults/AliasIRInterface/formalarrayactualcalleeuse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualcalleeuse.B > t
diff t TestResults/AliasIRInterface/formalarrayactualcalleeuse.B.out

echo "Testing TestCases/Alias/formalarrayactualcalleeusesubscript.B, TestResults/AliasIRInterface/formalarrayactualcalleeusesubscript.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualcalleeusesubscript.B > t
diff t TestResults/AliasIRInterface/formalarrayactualcalleeusesubscript.B.out

echo "Testing TestCases/Alias/formalarrayactualsubscriptcalleeuse.B, TestResults/AliasIRInterface/formalarrayactualsubscriptcalleeuse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualsubscriptcalleeuse.B > t
diff t TestResults/AliasIRInterface/formalarrayactualsubscriptcalleeuse.B.out

echo "Testing TestCases/Alias/formalarrayactualcalleeusein.B, TestResults/AliasIRInterface/formalarrayactualcalleeusein.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualcalleeusein.B > t
diff t TestResults/AliasIRInterface/formalarrayactualcalleeusein.B.out

echo "Testing TestCases/Alias/formalarrayactualcalleeuseout.B, TestResults/AliasIRInterface/formalarrayactualcalleeuseout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualcalleeuseout.B > t
diff t TestResults/AliasIRInterface/formalarrayactualcalleeuseout.B.out

echo "Testing TestCases/Alias/formalarrayactualcalleeuseinout.B, TestResults/AliasIRInterface/formalarrayactualcalleeuseinout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualcalleeuseinout.B > t
diff t TestResults/AliasIRInterface/formalarrayactualcalleeuseinout.B.out

echo "Testing TestCases/Alias/formalarrayactualcalleedefwholearray.B, TestResults/AliasIRInterface/formalarrayactualcalleedefwholearray.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualcalleedefwholearray.B > t
diff t TestResults/AliasIRInterface/formalarrayactualcalleedefwholearray.B.out

echo "Testing TestCases/Alias/formalarrayactualcalleedef.B, TestResults/AliasIRInterface/formalarrayactualcalleedef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualcalleedef.B > t
diff t TestResults/AliasIRInterface/formalarrayactualcalleedef.B.out

echo "Testing TestCases/Alias/formalarrayactualcalleedefsubscript.B, TestResults/AliasIRInterface/formalarrayactualcalleedefsubscript.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualcalleedefsubscript.B > t
diff t TestResults/AliasIRInterface/formalarrayactualcalleedefsubscript.B.out

echo "Testing TestCases/Alias/formalarrayactualcalleesectiondef.B, TestResults/AliasIRInterface/formalarrayactualcalleesectiondef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualcalleesectiondef.B > t
diff t TestResults/AliasIRInterface/formalarrayactualcalleesectiondef.B.out

echo "Testing TestCases/Alias/formalarrayactualsubscriptcalleedef.B, TestResults/AliasIRInterface/formalarrayactualsubscriptcalleedef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualsubscriptcalleedef.B > t
diff t TestResults/AliasIRInterface/formalarrayactualsubscriptcalleedef.B.out

echo "Testing TestCases/Alias/formalarrayactualcalleedefout.B, TestResults/AliasIRInterface/formalarrayactualcalleedefout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualcalleedefout.B > t
diff t TestResults/AliasIRInterface/formalarrayactualcalleedefout.B.out

echo "Testing TestCases/Alias/formalarrayactualcalleedefinout.B, TestResults/AliasIRInterface/formalarrayactualcalleedefinout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalarrayactualcalleedefinout.B > t
diff t TestResults/AliasIRInterface/formalarrayactualcalleedefinout.B.out

echo "Testing TestCases/Alias/formalscalaractualcalleeuse.B, TestResults/AliasIRInterface/formalscalaractualcalleeuse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalscalaractualcalleeuse.B > t
diff t TestResults/AliasIRInterface/formalscalaractualcalleeuse.B.out

echo "Testing TestCases/Alias/formalscalaractualcalleeusein.B, TestResults/AliasIRInterface/formalscalaractualcalleeusein.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalscalaractualcalleeusein.B > t
diff t TestResults/AliasIRInterface/formalscalaractualcalleeusein.B.out

echo "Testing TestCases/Alias/formalscalaractualcalleeuseout.B, TestResults/AliasIRInterface/formalscalaractualcalleeuseout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalscalaractualcalleeuseout.B > t
diff t TestResults/AliasIRInterface/formalscalaractualcalleeuseout.B.out

echo "Testing TestCases/Alias/formalscalaractualcalleeuseinout.B, TestResults/AliasIRInterface/formalscalaractualcalleeuseinout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalscalaractualcalleeuseinout.B > t
diff t TestResults/AliasIRInterface/formalscalaractualcalleeuseinout.B.out

echo "Testing TestCases/Alias/formalscalaractualcalleedef.B, TestResults/AliasIRInterface/formalscalaractualcalleedef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalscalaractualcalleedef.B > t
diff t TestResults/AliasIRInterface/formalscalaractualcalleedef.B.out

echo "Testing TestCases/Alias/formalscalaractualcalleedefout.B, TestResults/AliasIRInterface/formalscalaractualcalleedefout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalscalaractualcalleedefout.B > t
diff t TestResults/AliasIRInterface/formalscalaractualcalleedefout.B.out

echo "Testing TestCases/Alias/formalscalaractualcalleedefinout.B, TestResults/AliasIRInterface/formalscalaractualcalleedefinout.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formalscalaractualcalleedefinout.B > t
diff t TestResults/AliasIRInterface/formalscalaractualcalleedefinout.B.out

echo "Testing TestCases/Alias/localarrayactualcalleeuse.B, TestResults/AliasIRInterface/localarrayactualcalleeuse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localarrayactualcalleeuse.B > t
diff t TestResults/AliasIRInterface/localarrayactualcalleeuse.B.out

echo "Testing TestCases/Alias/localarrayactualcalleedefwholearray.B, TestResults/AliasIRInterface/localarrayactualcalleedefwholearray.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localarrayactualcalleedefwholearray.B > t
diff t TestResults/AliasIRInterface/localarrayactualcalleedefwholearray.B.out

echo "Testing TestCases/Alias/localarrayactualcalleedef.B, TestResults/AliasIRInterface/localarrayactualcalleedef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localarrayactualcalleedef.B > t
diff t TestResults/AliasIRInterface/localarrayactualcalleedef.B.out

echo "Testing TestCases/Alias/localarraysubscriptactualcalleedef.B, TestResults/AliasIRInterface/localarraysubscriptactualcalleedef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localarraysubscriptactualcalleedef.B > t
diff t TestResults/AliasIRInterface/localarraysubscriptactualcalleedef.B.out

echo "Testing TestCases/Alias/localarraysectionactualcalleedef.B, TestResults/AliasIRInterface/localarraysectionactualcalleedef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localarraysectionactualcalleedef.B > t
diff t TestResults/AliasIRInterface/localarraysectionactualcalleedef.B.out

echo "Testing TestCases/Alias/localscalaractualcalleeuse.B, TestResults/AliasIRInterface/localscalaractualcalleeuse.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localscalaractualcalleeuse.B > t
diff t TestResults/AliasIRInterface/localscalaractualcalleeuse.B.out

echo "Testing TestCases/Alias/localscalaractualcalleedef.B, TestResults/AliasIRInterface/localscalaractualcalleedef.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/localscalaractualcalleedef.B > t
diff t TestResults/AliasIRInterface/localscalaractualcalleedef.B.out

echo "Testing TestCases/Alias/formal_actual_expression.B, TestResults/AliasIRInterface/formal_actual_expression.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/formal_actual_expression.B > t
diff t TestResults/AliasIRInterface/formal_actual_expression.B.out

echo "Testing TestCases/Alias/local_actual_expression.B, TestResults/AliasIRInterface/local_actual_expression.B.out checked by PLM 09/28/07"
./FORTRANtoOA TestCases/Alias/local_actual_expression.B > t
diff t TestResults/AliasIRInterface/local_actual_expression.B.out

echo "Testing TestCases/Alias/formal_array_subscript_actual.B, TestResults/AliasIRInterface/formal_array_subscript_actual.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/formal_array_subscript_actual.B > t
diff t TestResults/AliasIRInterface/formal_array_subscript_actual.B.out

echo "Testing TestCases/Alias/local_array_subscript_actual.B, TestResults/AliasIRInterface/local_array_subscript_actual.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/local_array_subscript_actual.B > t
diff t TestResults/AliasIRInterface/local_array_subscript_actual.B.out

echo "Testing TestCases/Alias/formal_scalar_actual.B, TestResults/AliasIRInterface/formal_scalar_actual.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/formal_scalar_actual.B > t
diff t TestResults/AliasIRInterface/formal_scalar_actual.B.out

echo "Testing TestCases/Alias/local_scalar_actual.B, TestResults/AliasIRInterface/local_scalar_actual.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/local_scalar_actual.B > t
diff t TestResults/AliasIRInterface/local_scalar_actual.B.out

echo "Testing TestCases/Alias/formal_array_actual.B, TestResults/AliasIRInterface/formal_array_actual.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/formal_array_actual.B > t
diff t TestResults/AliasIRInterface/formal_array_actual.B.out

echo "Testing TestCases/Alias/local_array_actual.B, TestResults/AliasIRInterface/local_array_actual.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/local_array_actual.B > t
diff t TestResults/AliasIRInterface/local_array_actual.B.out

echo "Testing TestCases/Alias/formal_array_subscript_actual_in.B, TestResults/AliasIRInterface/formal_array_subscript_actual_in.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/formal_array_subscript_actual_in.B > t
diff t TestResults/AliasIRInterface/formal_array_subscript_actual_in.B.out

echo "Testing TestCases/Alias/formal_array_subscript_actual_out.B, TestResults/AliasIRInterface/formal_array_subscript_actual_out.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/formal_array_subscript_actual_out.B > t
diff t TestResults/AliasIRInterface/formal_array_subscript_actual_out.B.out

echo "Testing TestCases/Alias/formal_array_subscript_actual_inout.B, TestResults/AliasIRInterface/formal_array_subscript_actual_inout.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/formal_array_subscript_actual_inout.B > t
diff t TestResults/AliasIRInterface/formal_array_subscript_actual_inout.B.out

echo "Testing TestCases/Alias/formal_array_actual_in.B, TestResults/AliasIRInterface/formal_array_actual_in.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/formal_array_actual_in.B > t
diff t TestResults/AliasIRInterface/formal_array_actual_in.B.out

echo "Testing TestCases/Alias/formal_array_actual_out.B, TestResults/AliasIRInterface/formal_array_actual_out.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/formal_array_actual_out.B > t
diff t TestResults/AliasIRInterface/formal_array_actual_out.B.out

echo "Testing TestCases/Alias/formal_array_actual_inout.B, TestResults/AliasIRInterface/formal_array_actual_inout.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/formal_array_actual_inout.B > t
diff t TestResults/AliasIRInterface/formal_array_actual_inout.B.out

echo "Testing TestCases/Alias/local_actual_expression_assignment.B, TestResults/AliasIRInterface/local_actual_expression_assignment.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/local_actual_expression_assignment.B > t
diff t TestResults/AliasIRInterface/local_actual_expression_assignment.B.out

echo "Testing TestCases/Alias/formal_scalar_actual_in.B, TestResults/AliasIRInterface/formal_scalar_actual_in.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/formal_scalar_actual_in.B > t
diff t TestResults/AliasIRInterface/formal_scalar_actual_in.B.out

echo "Testing TestCases/Alias/formal_scalar_actual_out.B, TestResults/AliasIRInterface/formal_scalar_actual_out.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/formal_scalar_actual_out.B > t
diff t TestResults/AliasIRInterface/formal_scalar_actual_out.B.out

echo "Testing TestCases/Alias/formal_scalar_actual_inout.B, TestResults/AliasIRInterface/formal_scalar_actual_inout.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/formal_scalar_actual_inout.B > t
diff t TestResults/AliasIRInterface/formal_scalar_actual_inout.B.out

echo "Testing TestCases/Alias/Intrinsic_min.B, TestResults/AliasIRInterface/Intrinsic_min.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/Intrinsic_min.B > t
diff t TestResults/AliasIRInterface/Intrinsic_min.B.out

echo "Testing TestCases/Alias/Intrinsic_max.B, TestResults/AliasIRInterface/Intrinsic_max.B.out checked by PLM 09/29/07"
./FORTRANtoOA TestCases/Alias/Intrinsic_max.B > t
diff t TestResults/AliasIRInterface/Intrinsic_max.B.out

echo "Testing TestCases/Alias/localPointerToScalarAssignment.B, TestResults/AliasIRInterface/localPointerToScalarAssignment.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/localPointerToScalarAssignment.B > t
diff t TestResults/AliasIRInterface/localPointerToScalarAssignment.B.out

echo "Testing TestCases/Alias/formalPointerToScalarAssignment.B, TestResults/AliasIRInterface/formalPointerToScalarAssignment.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/formalPointerToScalarAssignment.B > t
diff t TestResults/AliasIRInterface/formalPointerToScalarAssignment.B.out

echo "Testing TestCases/Alias/localPointerToArrayAssignment.B, TestResults/AliasIRInterface/localPointerToArrayAssignment.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/localPointerToArrayAssignment.B > t
diff t TestResults/AliasIRInterface/localPointerToArrayAssignment.B.out

echo "Testing TestCases/Alias/formalPointerToArrayAssignment.B, TestResults/AliasIRInterface/formalPointerToArrayAssignment.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/formalPointerToArrayAssignment.B > t
diff t TestResults/AliasIRInterface/formalPointerToArrayAssignment.B.out

echo "Testing TestCases/Alias/DerefLocalPointerToScalarUse.B, TestResults/AliasIRInterface/DerefLocalPointerToScalarUse.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefLocalPointerToScalarUse.B > t
diff t TestResults/AliasIRInterface/DerefLocalPointerToScalarUse.B.out

echo "Testing TestCases/Alias/DerefLocalPointerToScalarDef.B, TestResults/AliasIRInterface/DerefLocalPointerToScalarDef.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefLocalPointerToScalarDef.B > t
diff t TestResults/AliasIRInterface/DerefLocalPointerToScalarDef.B.out

echo "Testing TestCases/Alias/DerefFormalPointerToScalarUse.B, TestResults/AliasIRInterface/DerefFormalPointerToScalarUse.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefFormalPointerToScalarUse.B > t
diff t TestResults/AliasIRInterface/DerefFormalPointerToScalarUse.B.out

echo "Testing TestCases/Alias/DerefFormalPointerToScalarDef.B, TestResults/AliasIRInterface/DerefFormalPointerToScalarDef.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefFormalPointerToScalarDef.B > t
diff t TestResults/AliasIRInterface/DerefFormalPointerToScalarDef.B.out

echo "Testing TestCases/Alias/DerefLocalPointerToArraySubscriptUse.B, TestResults/AliasIRInterface/DerefLocalPointerToArraySubscriptUse.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefLocalPointerToArraySubscriptUse.B > t
diff t TestResults/AliasIRInterface/DerefLocalPointerToArraySubscriptUse.B.out

echo "Testing TestCases/Alias/DerefLocalPointerToArraySubscriptDef.B, TestResults/AliasIRInterface/DerefLocalPointerToArraySubscriptDef.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefLocalPointerToArraySubscriptDef.B > t
diff t TestResults/AliasIRInterface/DerefLocalPointerToArraySubscriptDef.B.out

echo "Testing TestCases/Alias/DerefLocalPointerToArraySectionUse.B, TestResults/AliasIRInterface/DerefLocalPointerToArraySectionUse.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefLocalPointerToArraySectionUse.B > t
diff t TestResults/AliasIRInterface/DerefLocalPointerToArraySectionUse.B.out

echo "Testing TestCases/Alias/DerefLocalPointerToArraySectionDef.B, TestResults/AliasIRInterface/DerefLocalPointerToArraySectionDef.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefLocalPointerToArraySectionDef.B > t
diff t TestResults/AliasIRInterface/DerefLocalPointerToArraySectionDef.B.out

echo "Testing TestCases/Alias/DerefFormalPointerToArraySubscriptUse.B, TestResults/AliasIRInterface/DerefFormalPointerToArraySubscriptUse.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefFormalPointerToArraySubscriptUse.B > t
diff t TestResults/AliasIRInterface/DerefFormalPointerToArraySubscriptUse.B.out

echo "Testing TestCases/Alias/DerefFormalPointerToArraySubscriptDef.B, TestResults/AliasIRInterface/DerefFormalPointerToArraySubscriptDef.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefFormalPointerToArraySubscriptDef.B > t
diff t TestResults/AliasIRInterface/DerefFormalPointerToArraySubscriptDef.B.out

echo "Testing TestCases/Alias/DerefFormalPointerToArraySectionUse.B, TestResults/AliasIRInterface/DerefFormalPointerToArraySectionUse.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefFormalPointerToArraySectionUse.B > t
diff t TestResults/AliasIRInterface/DerefFormalPointerToArraySectionUse.B.out

echo "Testing TestCases/Alias/DerefFormalPointerToArraySectionDef.B, TestResults/AliasIRInterface/DerefFormalPointerToArraySectionDef.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefFormalPointerToArraySectionDef.B > t
diff t TestResults/AliasIRInterface/DerefFormalPointerToArraySectionDef.B.out

echo "Testing TestCases/Alias/DerefLocalPointerToScalarAsActual.B, TestResults/AliasIRInterface/DerefLocalPointerToScalarAsActual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefLocalPointerToScalarAsActual.B > t
diff t TestResults/AliasIRInterface/DerefLocalPointerToScalarAsActual.B.out

echo "Testing TestCases/Alias/DerefFormalPointerToScalarAsActual.B, TestResults/AliasIRInterface/DerefFormalPointerToScalarAsActual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefFormalPointerToScalarAsActual.B > t
diff t TestResults/AliasIRInterface/DerefFormalPointerToScalarAsActual.B.out

echo "Testing TestCases/Alias/DerefLocalPointerToArraySubscriptAsActual.B, TestResults/AliasIRInterface/DerefLocalPointerToArraySubscriptAsActual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefLocalPointerToArraySubscriptAsActual.B > t
diff t TestResults/AliasIRInterface/DerefLocalPointerToArraySubscriptAsActual.B.out

echo "Testing TestCases/Alias/DerefLocalPointerToArraySectionAsActual.B, TestResults/AliasIRInterface/DerefLocalPointerToArraySectionAsActual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefLocalPointerToArraySectionAsActual.B > t
diff t TestResults/AliasIRInterface/DerefLocalPointerToArraySectionAsActual.B.out

echo "Testing TestCases/Alias/DerefFormalPointerToArraySubscriptAsActual.B, TestResults/AliasIRInterface/DerefFormalPointerToArraySubscriptAsActual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefFormalPointerToArraySubscriptAsActual.B > t
diff t TestResults/AliasIRInterface/DerefFormalPointerToArraySubscriptAsActual.B.out

echo "Testing TestCases/Alias/DerefFormalPointerToArraySectionAsActual.B, TestResults/AliasIRInterface/DerefFormalPointerToArraySectionAsActual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/DerefFormalPointerToArraySectionAsActual.B > t
diff t TestResults/AliasIRInterface/DerefFormalPointerToArraySectionAsActual.B.out

echo "Testing TestCases/Alias/LocalPointerToScalarAsActual.B, TestResults/AliasIRInterface/LocalPointerToScalarAsActual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/LocalPointerToScalarAsActual.B > t
diff t TestResults/AliasIRInterface/LocalPointerToScalarAsActual.B.out

echo "Testing TestCases/Alias/FormalPointerToScalarAsActual.B, TestResults/AliasIRInterface/FormalPointerToScalarAsActual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/FormalPointerToScalarAsActual.B > t
diff t TestResults/AliasIRInterface/FormalPointerToScalarAsActual.B.out

echo "Testing TestCases/Alias/localPointerToArrayAsActual.B, TestResults/AliasIRInterface/localPointerToArrayAsActual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/localPointerToArrayAsActual.B > t
diff t TestResults/AliasIRInterface/localPointerToArrayAsActual.B.out

echo "Testing TestCases/Alias/formalPointerToArrayAsActual.B, TestResults/AliasIRInterface/formalPointerToArrayAsActual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/formalPointerToArrayAsActual.B > t
diff t TestResults/AliasIRInterface/formalPointerToArrayAsActual.B.out

echo "Testing TestCases/Alias/allocate_localpointertoarrayAsactualsubscript.B, TestResults/AliasIRInterface/allocate_localpointertoarrayAsactualsubscript.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/allocate_localpointertoarrayAsactualsubscript.B > t
diff t TestResults/AliasIRInterface/allocate_localpointertoarrayAsactualsubscript.B.out

echo "Testing TestCases/Alias/allocate_formalpointertoarrayAsactualsubscript.B, TestResults/AliasIRInterface/allocate_formalpointertoarrayAsactualsubscript.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/allocate_formalpointertoarrayAsactualsubscript.B > t
diff t TestResults/AliasIRInterface/allocate_formalpointertoarrayAsactualsubscript.B.out

echo "Testing TestCases/Alias/allocate_localpointertoarrayAsactualsection.B, TestResults/AliasIRInterface/allocate_localpointertoarrayAsactualsection.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/allocate_localpointertoarrayAsactualsection.B > t
diff t TestResults/AliasIRInterface/allocate_localpointertoarrayAsactualsection.B.out

echo "Testing TestCases/Alias/allocate_formalpointertoarrayAsactualsection.B, TestResults/AliasIRInterface/allocate_formalpointertoarrayAsactualsection.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/allocate_formalpointertoarrayAsactualsection.B > t
diff t TestResults/AliasIRInterface/allocate_formalpointertoarrayAsactualsection.B.out

echo "Testing TestCases/Alias/allocate_localarraysubscriptAsactual.B, TestResults/AliasIRInterface/allocate_localarraysubscriptAsactual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/allocate_localarraysubscriptAsactual.B > t
diff t TestResults/AliasIRInterface/allocate_localarraysubscriptAsactual.B.out

echo "Testing TestCases/Alias/allocate_localarraysectionAsactual.B, TestResults/AliasIRInterface/allocate_localarraysectionAsactual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/allocate_localarraysectionAsactual.B > t
diff t TestResults/AliasIRInterface/allocate_localarraysectionAsactual.B.out

echo "Testing TestCases/Alias/local_structvar_scalar_element_single_deref.B, TestResults/AliasIRInterface/local_structvar_scalar_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structvar_scalar_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_structvar_scalar_element_single_deref.B.out

echo "Testing TestCases/Alias/local_structvar_pointer_element_single_deref.B, TestResults/AliasIRInterface/local_structvar_pointer_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structvar_pointer_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_structvar_pointer_element_single_deref.B.out

echo "Testing TestCases/Alias/local_structvar_array_subscript_element_single_deref.B, TestResults/AliasIRInterface/local_structvar_array_subscript_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structvar_array_subscript_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_structvar_array_subscript_element_single_deref.B.out

echo "Testing TestCases/Alias/local_structvar_array_element_single_deref.B, TestResults/AliasIRInterface/local_structvar_array_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structvar_array_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_structvar_array_element_single_deref.B.out

echo "Testing TestCases/Alias/local_structvar_array_setion_element_single_deref.B, TestResults/AliasIRInterface/local_structvar_array_setion_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structvar_array_setion_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_structvar_array_setion_element_single_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_scalar_element_single_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_scalar_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_scalar_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_scalar_element_single_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_pointer_element_single_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_pointer_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_pointer_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_pointer_element_single_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_array_subscript_element_single_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_subscript_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_array_subscript_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_subscript_element_single_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_array_element_single_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_array_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_element_single_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_array_section_element_single_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_section_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_array_section_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_section_element_single_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_scalar_element_single_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_scalar_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_scalar_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_scalar_element_single_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_array_subscript_element_single_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_array_subscript_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_array_subscript_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_array_subscript_element_single_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_section_scalar_element_single_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_section_scalar_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_section_scalar_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_section_scalar_element_single_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_section_array_subscript_element_single_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_section_array_subscript_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_section_array_subscript_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_section_array_subscript_element_single_deref.B.out

echo "Testing TestCases/Alias/local_structPointer_scalar_element_single_deref.B, TestResults/AliasIRInterface/local_structPointer_scalar_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structPointer_scalar_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_structPointer_scalar_element_single_deref.B.out

echo "Testing TestCases/Alias/local_structPointer_array_subscript_element_single_deref.B, TestResults/AliasIRInterface/local_structPointer_array_subscript_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structPointer_array_subscript_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_structPointer_array_subscript_element_single_deref.B.out

echo "Testing TestCases/Alias/local_structPointer_pointer_element_single_deref.B, TestResults/AliasIRInterface/local_structPointer_pointer_element_single_deref.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structPointer_pointer_element_single_deref.B > t
diff t TestResults/AliasIRInterface/local_structPointer_pointer_element_single_deref.B.out

echo "Testing TestCases/Alias/local_structvar_scalar_element_single_deref_actual.B, TestResults/AliasIRInterface/local_structvar_scalar_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structvar_scalar_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_structvar_scalar_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_structvar_scalar_element_single_deref_actual.B, TestResults/AliasIRInterface/local_structvar_scalar_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structvar_scalar_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_structvar_scalar_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_structvar_array_subscript_element_single_deref_actual.B, TestResults/AliasIRInterface/local_structvar_array_subscript_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structvar_array_subscript_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_structvar_array_subscript_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_structvar_array_element_single_deref_actual.B, TestResults/AliasIRInterface/local_structvar_array_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structvar_array_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_structvar_array_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_structvar_array_section_element_single_deref_actual.B, TestResults/AliasIRInterface/local_structvar_array_section_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structvar_array_section_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_structvar_array_section_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_scalar_element_single_deref_actual.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_scalar_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_scalar_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_scalar_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_array_subscript_element_single_deref_actual.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_subscript_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_array_subscript_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_subscript_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_array_element_single_deref_actual.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_array_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_array_section_element_single_deref_actual.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_section_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_array_section_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_section_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_scalar_element_single_deref_actual.B, TestResults/AliasIRInterface/local_arrayOfstruct_scalar_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_scalar_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_scalar_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_array_subscript_element_single_deref_actual.B, TestResults/AliasIRInterface/local_arrayOfstruct_array_subscript_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_array_subscript_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_array_subscript_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_section_scalar_element_single_deref_actual.B, TestResults/AliasIRInterface/local_arrayOfstruct_section_scalar_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_section_scalar_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_section_scalar_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_section_array_subscript_element_single_deref_actual.B, TestResults/AliasIRInterface/local_arrayOfstruct_section_array_subscript_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_section_array_subscript_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_section_array_subscript_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_structPointer_scalar_element_single_deref_actual.B, TestResults/AliasIRInterface/local_structPointer_scalar_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structPointer_scalar_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_structPointer_scalar_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_structPointer_array_subscript_element_single_deref_actual.B, TestResults/AliasIRInterface/local_structPointer_array_subscript_element_single_deref_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structPointer_array_subscript_element_single_deref_actual.B > t
diff t TestResults/AliasIRInterface/local_structPointer_array_subscript_element_single_deref_actual.B.out

echo "Testing TestCases/Alias/local_structvar_assignment.B, TestResults/AliasIRInterface/local_structvar_assignment.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structvar_assignment.B > t
diff t TestResults/AliasIRInterface/local_structvar_assignment.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_assignment.B, TestResults/AliasIRInterface/local_arrayOfstruct_assignment.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_assignment.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_assignment.B.out

echo "Testing TestCases/Alias/local_structPointer_assignment.B, TestResults/AliasIRInterface/local_structPointer_assignment.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structPointer_assignment.B > t
diff t TestResults/AliasIRInterface/local_structPointer_assignment.B.out

echo "Testing TestCases/Alias/local_structPointer_to_structvar_assignment.B, TestResults/AliasIRInterface/local_structPointer_to_structvar_assignment.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structPointer_to_structvar_assignment.B > t
diff t TestResults/AliasIRInterface/local_structPointer_to_structvar_assignment.B.out

echo "Testing TestCases/Alias/local_structvar_actual.B, TestResults/AliasIRInterface/local_structvar_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_structvar_actual.B > t
diff t TestResults/AliasIRInterface/local_structvar_actual.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_actual.B, TestResults/AliasIRInterface/local_arrayOfstruct_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_actual.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_actual.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_actual.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_actual.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_actual.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_section_actual.B, TestResults/AliasIRInterface/local_arrayOfstruct_section_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_section_actual.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_section_actual.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_pointer_actual.B, TestResults/AliasIRInterface/local_arrayOfstruct_pointer_actual.B.out checked by PLM 09/21/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_pointer_actual.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_pointer_actual.B.out

echo "Testing TestCases/Alias/local_structvar_scalar_element_double_deref.B, TestResults/AliasIRInterface/local_structvar_scalar_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_structvar_scalar_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_structvar_scalar_element_double_deref.B.out

echo "Testing TestCases/Alias/local_structvar_pointer_element_double_deref.B, TestResults/AliasIRInterface/local_structvar_pointer_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_structvar_pointer_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_structvar_pointer_element_double_deref.B.out

echo "Testing TestCases/Alias/local_structvar_array_subscript_element_double_deref.B, TestResults/AliasIRInterface/local_structvar_array_subscript_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_structvar_array_subscript_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_structvar_array_subscript_element_double_deref.B.out

echo "Testing TestCases/Alias/local_structvar_array_element_double_deref.B, TestResults/AliasIRInterface/local_structvar_array_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_structvar_array_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_structvar_array_element_double_deref.B.out

echo "Testing TestCases/Alias/local_structvar_array_section_element_double_deref.B, TestResults/AliasIRInterface/local_structvar_array_section_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_structvar_array_section_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_structvar_array_section_element_double_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_scalar_element_double_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_scalar_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_scalar_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_scalar_element_double_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_pointer_element_double_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_pointer_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_pointer_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_pointer_element_double_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_array_subscript_element_double_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_subscript_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_array_subscript_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_subscript_element_double_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_array_element_double_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_array_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_element_double_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_section_scalar_element_double_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_section_scalar_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_section_scalar_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_section_scalar_element_double_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_subscript_array_section_element_double_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_section_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_subscript_array_section_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_subscript_array_section_element_double_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_scalar_element_double_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_scalar_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_scalar_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_scalar_element_double_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_array_subscript_element_double_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_array_subscript_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_array_subscript_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_array_subscript_element_double_deref.B.out

echo "Testing TestCases/Alias/local_arrayOfstruct_section_array_subscript_element_double_deref.B, TestResults/AliasIRInterface/local_arrayOfstruct_section_array_subscript_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_arrayOfstruct_section_array_subscript_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_arrayOfstruct_section_array_subscript_element_double_deref.B.out

echo "Testing TestCases/Alias/local_structPointer_scalar_element_double_deref.B, TestResults/AliasIRInterface/local_structPointer_scalar_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_structPointer_scalar_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_structPointer_scalar_element_double_deref.B.out

echo "Testing TestCases/Alias/local_structPointer_array_subscript_element_double_deref.B, TestResults/AliasIRInterface/local_structPointer_array_subscript_element_double_deref.B.out checked by PLM 09/22/07"
./FORTRANtoOA TestCases/Alias/local_structPointer_array_subscript_element_double_deref.B > t
diff t TestResults/AliasIRInterface/local_structPointer_array_subscript_element_double_deref.B.out

