echo "Testing TestCases/MemRefExpr/arrays1.B, TestResults/MemRefExpr/arrays1.B.out conservatively correct MMS 7/5/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/arrays1.B > t
diff t TestResults/MemRefExpr/arrays1.B.out

echo "Testing TestCases/MemRefExpr/arrays5.B, TestResults/MemRefExpr/arrays5.B.out checked by MMS 7/5/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/arrays5.B > t
diff t TestResults/MemRefExpr/arrays5.B.out

echo "Testing TestCases/MemRefExpr/functions1.B, TestResults/MemRefExpr/functions1.B.out checked by MMS 7/5/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/functions1.B > t
diff t TestResults/MemRefExpr/functions1.B.out

echo "Testing TestCases/MemRefExpr/head_tlm_driver_g.pre.B, TestResults/MemRefExpr/head_tlm_driver_g.pre.B.out not correct on defs to fields MMS 7/5/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/head_tlm_driver_g.pre.B > t
diff t TestResults/MemRefExpr/head_tlm_driver_g.pre.B.out

echo "Testing TestCases/MemRefExpr/interalias_proc_call1.B, TestResults/MemRefExpr/interalias_proc_call1.B.out checked by MMS 7/5/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/interalias_proc_call1.B > t
diff t TestResults/MemRefExpr/interalias_proc_call1.B.out

echo "Testing TestCases/MemRefExpr/interalias_proc_call2.B, TestResults/MemRefExpr/interalias_proc_call2.B.out checked by MMS 7/5/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/interalias_proc_call2.B > t
diff t TestResults/MemRefExpr/interalias_proc_call2.B.out

echo "Testing TestCases/MemRefExpr/interalias_proc_call3.B, TestResults/MemRefExpr/interalias_proc_call3.B.out checked by MMS 7/5/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/interalias_proc_call3.B > t
diff t TestResults/MemRefExpr/interalias_proc_call3.B.out

echo "Testing TestCases/MemRefExpr/formal_actual_expression.B, TestResults/MemRefExpr/formal_actual_expression.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/formal_actual_expression.B > t
diff t TestResults/MemRefExpr/formal_actual_expression.B.out

echo "Testing TestCases/MemRefExpr/local_actual_expression.B, TestResults/MemRefExpr/local_actual_expression.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/local_actual_expression.B > t
diff t TestResults/MemRefExpr/local_actual_expression.B.out

echo "Testing TestCases/MemRefExpr/formal_array_subscript_actual.B, TestResults/MemRefExpr/formal_array_subscript_actual.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/formal_array_subscript_actual.B > t
diff t TestResults/MemRefExpr/formal_array_subscript_actual.B.out

echo "Testing TestCases/MemRefExpr/local_array_subscript_actual.B, TestResults/MemRefExpr/local_array_subscript_actual.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/local_array_subscript_actual.B > t
diff t TestResults/MemRefExpr/local_array_subscript_actual.B.out

echo "Testing TestCases/MemRefExpr/formal_scalar_actual.B, TestResults/MemRefExpr/formal_scalar_actual.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/formal_scalar_actual.B > t
diff t TestResults/MemRefExpr/formal_scalar_actual.B.out

echo "Testing TestCases/MemRefExpr/local_scalar_actual.B, TestResults/MemRefExpr/local_scalar_actual.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/local_scalar_actual.B > t
diff t TestResults/MemRefExpr/local_scalar_actual.B.out

echo "Testing TestCases/MemRefExpr/formal_array_actual.B, TestResults/MemRefExpr/formal_array_actual.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/formal_array_actual.B > t
diff t TestResults/MemRefExpr/formal_array_actual.B.out

echo "Testing TestCases/MemRefExpr/local_array_actual.B, TestResults/MemRefExpr/local_array_actual.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/local_array_actual.B > t
diff t TestResults/MemRefExpr/local_array_actual.B.out

echo "Testing TestCases/MemRefExpr/formal_array_subscript_actual_in.B, TestResults/MemRefExpr/formal_array_subscript_actual_in.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/formal_array_subscript_actual_in.B > t
diff t TestResults/MemRefExpr/formal_array_subscript_actual_in.B.out

echo "Testing TestCases/MemRefExpr/formal_array_subscript_actual_out.B, TestResults/MemRefExpr/formal_array_subscript_actual_out.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/formal_array_subscript_actual_out.B > t
diff t TestResults/MemRefExpr/formal_array_subscript_actual_out.B.out

echo "Testing TestCases/MemRefExpr/formal_array_subscript_actual_inout.B, TestResults/MemRefExpr/formal_array_subscript_actual_inout.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/formal_array_subscript_actual_inout.B > t
diff t TestResults/MemRefExpr/formal_array_subscript_actual_inout.B.out

echo "Testing TestCases/MemRefExpr/formal_array_actual_in.B, TestResults/MemRefExpr/formal_array_actual_in.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/formal_array_actual_in.B > t
diff t TestResults/MemRefExpr/formal_array_actual_in.B.out

echo "Testing TestCases/MemRefExpr/formal_array_actual_out.B, TestResults/MemRefExpr/formal_array_actual_out.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/formal_array_actual_out.B > t
diff t TestResults/MemRefExpr/formal_array_actual_out.B.out

echo "Testing TestCases/MemRefExpr/formal_array_actual_inout.B, TestResults/MemRefExpr/formal_array_actual_inout.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/formal_array_actual_inout.B > t
diff t TestResults/MemRefExpr/formal_array_actual_inout.B.out

echo "Testing TestCases/MemRefExpr/local_actual_expression_assignment.B, TestResults/MemRefExpr/local_actual_expression_assignment.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/local_actual_expression_assignment.B > t
diff t TestResults/MemRefExpr/local_actual_expression_assignment.B.out

echo "Testing TestCases/MemRefExpr/formal_scalar_actual_in.B, TestResults/MemRefExpr/formal_scalar_actual_in.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/formal_scalar_actual_in.B > t
diff t TestResults/MemRefExpr/formal_scalar_actual_in.B.out

echo "Testing TestCases/MemRefExpr/formal_scalar_actual_out.B, TestResults/MemRefExpr/formal_scalar_actual_out.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/formal_scalar_actual_out.B > t
diff t TestResults/MemRefExpr/formal_scalar_actual_out.B.out

echo "Testing TestCases/MemRefExpr/formal_scalar_actual_inout.B, TestResults/MemRefExpr/formal_scalar_actual_inout.B.out checked by PLM 10/16/06"
./test-open64 --oa-MemRefExpr TestCases/MemRefExpr/formal_scalar_actual_inout.B > t
diff t TestResults/MemRefExpr/formal_scalar_actual_inout.B.out

