${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/CSReachConsts/constprop_if1a.f90
mv -f constprop_if1a.B TestCases/CSReachConsts/constprop_if1a.B
echo "Testing TestCases/CSReachConsts/constprop_if1a.B, TestResults/CSReachConsts/constprop_if1a.B.out Checked by BK 07/08/09"
./test-open64 --oa-ICFGCSReachConsts TestCases/CSReachConsts/constprop_if1a.B > t
diff -I "LOC 0 0 source files:" t TestResults/CSReachConsts/constprop_if1a.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/CSReachConsts/constprop_if1.f90
mv -f constprop_if1.B TestCases/CSReachConsts/constprop_if1.B
echo "Testing TestCases/CSReachConsts/constprop_if1.B, TestResults/CSReachConsts/constprop_if1.B.out Checked by BK 07/08/09"
./test-open64 --oa-ICFGCSReachConsts TestCases/CSReachConsts/constprop_if1.B > t
diff -I "LOC 0 0 source files:" t TestResults/CSReachConsts/constprop_if1.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/CSReachConsts/constprop_if1b.f90
mv -f constprop_if1b.B TestCases/CSReachConsts/constprop_if1b.B
echo "Testing TestCases/CSReachConsts/constprop_if1b.B, TestResults/CSReachConsts/constprop_if1b.B.out Checked by BK 07/08/09"
./test-open64 --oa-ICFGCSReachConsts TestCases/CSReachConsts/constprop_if1b.B > t
diff -I "LOC 0 0 source files:" t TestResults/CSReachConsts/constprop_if1b.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/CSReachConsts/constprop_if1c.f90
mv -f constprop_if1c.B TestCases/CSReachConsts/constprop_if1c.B
echo "Testing TestCases/CSReachConsts/constprop_if1c.B, TestResults/CSReachConsts/constprop_if1c.B.out Checked by BK 07/08/09"
./test-open64 --oa-ICFGCSReachConsts TestCases/CSReachConsts/constprop_if1c.B > t
diff -I "LOC 0 0 source files:" t TestResults/CSReachConsts/constprop_if1c.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/CSReachConsts/constprop_loop1.f90
mv -f constprop_loop1.B TestCases/CSReachConsts/constprop_loop1.B
echo "Testing TestCases/CSReachConsts/constprop_loop1.B, TestResults/CSReachConsts/constprop_loop1.B.out Checked by BK 07/08/09"
./test-open64 --oa-ICFGCSReachConsts TestCases/CSReachConsts/constprop_loop1.B > t
diff -I "LOC 0 0 source files:" t TestResults/CSReachConsts/constprop_loop1.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/CSReachConsts/constprop_loop2.f90
mv -f constprop_loop2.B TestCases/CSReachConsts/constprop_loop2.B
echo "Testing TestCases/CSReachConsts/constprop_loop2.B, TestResults/CSReachConsts/constprop_loop2.B.out Checked by BK 07/08/09"
./test-open64 --oa-ICFGCSReachConsts TestCases/CSReachConsts/constprop_loop2.B > t
diff -I "LOC 0 0 source files:" t TestResults/CSReachConsts/constprop_loop2.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/CSReachConsts/constprop_proc1.f90
mv -f constprop_proc1.B TestCases/CSReachConsts/constprop_proc1.B
echo "Testing TestCases/CSReachConsts/constprop_proc1.B, TestResults/CSReachConsts/constprop_proc1.B.out Checked by BK 07/09/09"
./test-open64 --oa-ICFGCSReachConsts TestCases/CSReachConsts/constprop_proc1.B > t
diff -I "LOC 0 0 source files:" t TestResults/CSReachConsts/constprop_proc1.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/CSReachConsts/constprop_proc2.f90
mv -f constprop_proc2.B TestCases/CSReachConsts/constprop_proc2.B
echo "Testing TestCases/CSReachConsts/constprop_proc2.B, TestResults/CSReachConsts/constprop_proc2.B.out Checked by BK 07/09/09"
./test-open64 --oa-ICFGCSReachConsts TestCases/CSReachConsts/constprop_proc2.B > t
diff -I "LOC 0 0 source files:" t TestResults/CSReachConsts/constprop_proc2.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/CSReachConsts/constprop_proc3.f90
mv -f constprop_proc3.B TestCases/CSReachConsts/constprop_proc3.B
echo "Testing TestCases/CSReachConsts/constprop_proc3.B, TestResults/CSReachConsts/constprop_proc3.B.out Checked by BK 07/09/09"
./test-open64 --oa-ICFGCSReachConsts TestCases/CSReachConsts/constprop_proc3.B > t
diff -I "LOC 0 0 source files:" t TestResults/CSReachConsts/constprop_proc3.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/CSReachConsts/multiple_calls8.f
mv -f multiple_calls8.B TestCases/CSReachConsts/multiple_calls8.B
echo "Testing TestCases/CSReachConsts/multiple_calls8.B, TestResults/CSReachConsts/multiple_calls8.B--ccmax-2.out Checked by BK 08/25/09"
./test-open64 --oa-ICFGCSReachConsts --ccmax 2 TestCases/CSReachConsts/multiple_calls8.B > t
diff -I "LOC 0 0 source files:" t TestResults/CSReachConsts/multiple_calls8.B--ccmax-2.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/CSReachConsts/multiple_calls10.f
mv -f multiple_calls10.B TestCases/CSReachConsts/multiple_calls10.B
echo "Testing TestCases/CSReachConsts/multiple_calls10.B, TestResults/CSReachConsts/multiple_calls10.B--ccmax-2.out Checked by BK 10/15/09"
./test-open64 --oa-ICFGCSReachConsts --ccmax 2 TestCases/CSReachConsts/multiple_calls10.B > t
diff -I "LOC 0 0 source files:" t TestResults/CSReachConsts/multiple_calls10.B--ccmax-2.out

