echo "Testing TestCases/CSFIActivity/simple0.B, TestResults/CSFIActivity/simple0.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/simple0.B > t
diff t TestResults/CSFIActivity/simple0.B.out

echo "Testing TestCases/CSFIActivity/simple1.B, TestResults/CSFIActivity/simple1.B.out Checked by PLm 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/simple1.B > t
diff t TestResults/CSFIActivity/simple1.B.out

echo "Testing TestCases/CSFIActivity/simple2.B, TestResults/CSFIActivity/simple2.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/simple2.B > t
diff t TestResults/CSFIActivity/simple2.B.out

echo "Testing TestCases/CSFIActivity/simple3.B, TestResults/CSFIActivity/simple3.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/simple3.B > t
diff t TestResults/CSFIActivity/simple3.B.out

echo "Testing TestCases/CSFIActivity/argumentArrayIndex2.B, TestResults/CSFIActivity/argumentArrayIndex2.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/argumentArrayIndex2.B > t
diff t TestResults/CSFIActivity/argumentArrayIndex2.B.out

echo "Testing TestCases/CSFIActivity/argumentArrayIndex3.B, TestResults/CSFIActivity/argumentArrayIndex3.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/argumentArrayIndex3.B > t
diff t TestResults/CSFIActivity/argumentArrayIndex3.B.out

echo "Testing TestCases/CSFIActivity/argumentArrayIndex4.B, TestResults/CSFIActivity/argumentArrayIndex4.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/argumentArrayIndex4.B > t
diff t TestResults/CSFIActivity/argumentArrayIndex4.B.out

echo "Testing TestCases/CSFIActivity/argumentArrayIndex.B, TestResults/CSFIActivity/argumentArrayIndex.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/argumentArrayIndex.B > t
diff t TestResults/CSFIActivity/argumentArrayIndex.B.out

echo "Testing TestCases/CSFIActivity/argumentConversion_2.B, TestResults/CSFIActivity/argumentConversion_2.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/argumentConversion_2.B > t
diff t TestResults/CSFIActivity/argumentConversion_2.B.out

echo "Testing TestCases/CSFIActivity/argumentConversion_3.B, TestResults/CSFIActivity/argumentConversion_3.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/argumentConversion_3.B > t
diff t TestResults/CSFIActivity/argumentConversion_3.B.out

echo "Testing TestCases/CSFIActivity/argumentConversion_4.B, TestResults/CSFIActivity/argumentConversion_4.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/argumentConversion_4.B > t
diff t TestResults/CSFIActivity/argumentConversion_4.B.out

echo "Testing TestCases/CSFIActivity/bat.B, TestResults/CSFIActivity/bat.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/bat.B > t
diff t TestResults/CSFIActivity/bat.B.out

echo "Testing TestCases/CSFIActivity/cast1.B, TestResults/CSFIActivity/cast1.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/cast1.B > t
diff t TestResults/CSFIActivity/cast1.B.out

echo "Testing TestCases/CSFIActivity/ConstFoldSimp0.B, TestResults/CSFIActivity/ConstFoldSimp0.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/ConstFoldSimp0.B > t
diff t TestResults/CSFIActivity/ConstFoldSimp0.B.out

echo "Testing TestCases/CSFIActivity/constPrec.B, TestResults/CSFIActivity/constPrec.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/constPrec.B > t
diff t TestResults/CSFIActivity/constPrec.B.out

echo "Testing TestCases/CSFIActivity/daerfj.B, TestResults/CSFIActivity/daerfj.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/daerfj.B > t
diff t TestResults/CSFIActivity/daerfj.B.out

echo "Testing TestCases/CSFIActivity/directDependency1.B, TestResults/CSFIActivity/directDependency1.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/directDependency1.B > t
diff t TestResults/CSFIActivity/directDependency1.B.out

echo "Testing TestCases/CSFIActivity/directDependency2.B, TestResults/CSFIActivity/directDependency2.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/directDependency2.B > t
diff t TestResults/CSFIActivity/directDependency2.B.out

echo "Testing TestCases/CSFIActivity/directDependency3.B, TestResults/CSFIActivity/directDependency3.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/directDependency3.B > t
diff t TestResults/CSFIActivity/directDependency3.B.out

echo "Testing TestCases/CSFIActivity/float_intrinsic.B, TestResults/CSFIActivity/float_intrinsic.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/float_intrinsic.B > t
diff t TestResults/CSFIActivity/float_intrinsic.B.out

echo "Testing TestCases/CSFIActivity/globalActive_1.B, TestResults/CSFIActivity/globalActive_1.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/globalActive_1.B > t
diff t TestResults/CSFIActivity/globalActive_1.B.out

echo "Testing TestCases/CSFIActivity/globalActive_2.B, TestResults/CSFIActivity/globalActive_2.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/globalActive_2.B > t
diff t TestResults/CSFIActivity/globalActive_2.B.out

echo "Testing TestCases/CSFIActivity/globalActive_3.B, TestResults/CSFIActivity/globalActive_3.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/globalActive_3.B > t
diff t TestResults/CSFIActivity/globalActive_3.B.out

echo "Testing TestCases/CSFIActivity/globalActive_7.B, TestResults/CSFIActivity/globalActive_7.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/globalActive_7.B > t
diff t TestResults/CSFIActivity/globalActive_7.B.out

echo "Testing TestCases/CSFIActivity/If_Loop1.B, TestResults/CSFIActivity/If_Loop1.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/If_Loop1.B > t
diff t TestResults/CSFIActivity/If_Loop1.B.out

echo "Testing TestCases/CSFIActivity/If_Loop2.B, TestResults/CSFIActivity/If_Loop2.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/If_Loop2.B > t
diff t TestResults/CSFIActivity/If_Loop2.B.out

echo "Testing TestCases/CSFIActivity/If_Loop3.B, TestResults/CSFIActivity/If_Loop3.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/If_Loop3.B > t
diff t TestResults/CSFIActivity/If_Loop3.B.out

echo "Testing TestCases/CSFIActivity/If_Loop5.B, TestResults/CSFIActivity/If_Loop5.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/If_Loop5.B > t
diff t TestResults/CSFIActivity/If_Loop5.B.out

echo "Testing TestCases/CSFIActivity/IfStatement_1.B, TestResults/CSFIActivity/IfStatement_1.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/IfStatement_1.B > t
diff t TestResults/CSFIActivity/IfStatement_1.B.out

echo "Testing TestCases/CSFIActivity/IfStatement_2.B, TestResults/CSFIActivity/IfStatement_2.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/IfStatement_2.B > t
diff t TestResults/CSFIActivity/IfStatement_2.B.out

echo "Testing TestCases/CSFIActivity/lion.B, TestResults/CSFIActivity/lion.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/lion.B > t
diff t TestResults/CSFIActivity/lion.B.out

echo "Testing TestCases/CSFIActivity/Loop_1.B, TestResults/CSFIActivity/Loop_1.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_1.B > t
diff t TestResults/CSFIActivity/Loop_1.B.out

echo "Testing TestCases/CSFIActivity/Loop_2.B, TestResults/CSFIActivity/Loop_2.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_2.B > t
diff t TestResults/CSFIActivity/Loop_2.B.out

echo "Testing TestCases/CSFIActivity/Loop_3.B, TestResults/CSFIActivity/Loop_3.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_3.B > t
diff t TestResults/CSFIActivity/Loop_3.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_1.B, TestResults/CSFIActivity/Loop_simple_1.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_1.B > t
diff t TestResults/CSFIActivity/Loop_simple_1.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_2a.B, TestResults/CSFIActivity/Loop_simple_2a.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_2a.B > t
diff t TestResults/CSFIActivity/Loop_simple_2a.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_2.B, TestResults/CSFIActivity/Loop_simple_2.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_2.B > t
diff t TestResults/CSFIActivity/Loop_simple_2.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_3.B, TestResults/CSFIActivity/Loop_simple_3.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_3.B > t
diff t TestResults/CSFIActivity/Loop_simple_3.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_4.B, TestResults/CSFIActivity/Loop_simple_4.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_4.B > t
diff t TestResults/CSFIActivity/Loop_simple_4.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_5.B, TestResults/CSFIActivity/Loop_simple_5.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_5.B > t
diff t TestResults/CSFIActivity/Loop_simple_5.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_6.B, TestResults/CSFIActivity/Loop_simple_6.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_6.B > t
diff t TestResults/CSFIActivity/Loop_simple_6.B.out

echo "Testing TestCases/CSFIActivity/nested_calls_1.B, TestResults/CSFIActivity/nested_calls_1.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/nested_calls_1.B > t
diff t TestResults/CSFIActivity/nested_calls_1.B.out

echo "Testing TestCases/CSFIActivity/nested_calls_2.B, TestResults/CSFIActivity/nested_calls_2.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/nested_calls_2.B > t
diff t TestResults/CSFIActivity/nested_calls_2.B.out

echo "Testing TestCases/CSFIActivity/nested_calls_3.B, TestResults/CSFIActivity/nested_calls_3.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/nested_calls_3.B > t
diff t TestResults/CSFIActivity/nested_calls_3.B.out

echo "Testing TestCases/CSFIActivity/nested_calls_4.B, TestResults/CSFIActivity/nested_calls_4.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/nested_calls_4.B > t
diff t TestResults/CSFIActivity/nested_calls_4.B.out

echo "Testing TestCases/CSFIActivity/NestedIf.B, TestResults/CSFIActivity/NestedIf.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/NestedIf.B > t
diff t TestResults/CSFIActivity/NestedIf.B.out

echo "Testing TestCases/CSFIActivity/NestedLoopIf.B, TestResults/CSFIActivity/NestedLoopIf.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/NestedLoopIf.B > t
diff t TestResults/CSFIActivity/NestedLoopIf.B.out

echo "Testing TestCases/CSFIActivity/NestedLoops.B, TestResults/CSFIActivity/NestedLoops.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/NestedLoops.B > t
diff t TestResults/CSFIActivity/NestedLoops.B.out

echo "Testing TestCases/CSFIActivity/passiveStatement.B, TestResults/CSFIActivity/passiveStatement.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/passiveStatement.B > t
diff t TestResults/CSFIActivity/passiveStatement.B.out

echo "Testing TestCases/CSFIActivity/passiveSubroutine.B, TestResults/CSFIActivity/passiveSubroutine.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/passiveSubroutine.B > t
diff t TestResults/CSFIActivity/passiveSubroutine.B.out

echo "Testing TestCases/CSFIActivity/readWrite1.B, TestResults/CSFIActivity/readWrite1.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/readWrite1.B > t
diff t TestResults/CSFIActivity/readWrite1.B.out

echo "Testing TestCases/CSFIActivity/readWrite2.B, TestResults/CSFIActivity/readWrite2.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/readWrite2.B > t
diff t TestResults/CSFIActivity/readWrite2.B.out

echo "Testing TestCases/CSFIActivity/SeqOfIfs.B, TestResults/CSFIActivity/SeqOfIfs.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/SeqOfIfs.B > t
diff t TestResults/CSFIActivity/SeqOfIfs.B.out

echo "Testing TestCases/CSFIActivity/SeqOfLoops.B, TestResults/CSFIActivity/SeqOfLoops.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/SeqOfLoops.B > t
diff t TestResults/CSFIActivity/SeqOfLoops.B.out

echo "Testing TestCases/CSFIActivity/sideEffect_1.B, TestResults/CSFIActivity/sideEffect_1.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/sideEffect_1.B > t
diff t TestResults/CSFIActivity/sideEffect_1.B.out

echo "Testing TestCases/CSFIActivity/sideEffect_2.B, TestResults/CSFIActivity/sideEffect_2.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/sideEffect_2.B > t
diff t TestResults/CSFIActivity/sideEffect_2.B.out

echo "Testing TestCases/CSFIActivity/sideEffect_3.B, TestResults/CSFIActivity/sideEffect_3.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/sideEffect_3.B > t
diff t TestResults/CSFIActivity/sideEffect_3.B.out

echo "Testing TestCases/CSFIActivity/speelpenning.B, TestResults/CSFIActivity/speelpenning.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/speelpenning.B > t
diff t TestResults/CSFIActivity/speelpenning.B.out

echo "Testing TestCases/CSFIActivity/tanh_f_arg.B, TestResults/CSFIActivity/tanh_f_arg.B.out Checked by PLM 12/16/06"
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/tanh_f_arg.B > t
diff t TestResults/CSFIActivity/tanh_f_arg.B.out

echo "Testing TestCases/CSFIActivity/argumentConversion_1.B, TestResults/CSFIActivity/argumentConversion_1.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/argumentConversion_1.B > t
diff t TestResults/CSFIActivity/argumentConversion_1.B.out

echo "Testing TestCases/CSFIActivity/argumentConversion_4a.B, TestResults/CSFIActivity/argumentConversion_4a.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/argumentConversion_4a.B > t
diff t TestResults/CSFIActivity/argumentConversion_4a.B.out

echo "Testing TestCases/CSFIActivity/argumentConversion_5.B, TestResults/CSFIActivity/argumentConversion_5.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/argumentConversion_5.B > t
diff t TestResults/CSFIActivity/argumentConversion_5.B.out

echo "Testing TestCases/CSFIActivity/box_timestep.B, TestResults/CSFIActivity/box_timestep.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/box_timestep.B > t
diff t TestResults/CSFIActivity/box_timestep.B.out

echo "Testing TestCases/CSFIActivity/bratu.B, TestResults/CSFIActivity/bratu.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/bratu.B > t
diff t TestResults/CSFIActivity/bratu.B.out

echo "Testing TestCases/CSFIActivity/dfdcfj.B, TestResults/CSFIActivity/dfdcfj.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/dfdcfj.B > t
diff t TestResults/CSFIActivity/dfdcfj.B.out

echo "Testing TestCases/CSFIActivity/dfdcfj_MemOps.B, TestResults/CSFIActivity/dfdcfj_MemOps.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/dfdcfj_MemOps.B > t
diff t TestResults/CSFIActivity/dfdcfj_MemOps.B.out

echo "Testing TestCases/CSFIActivity/duudChains1.B, TestResults/CSFIActivity/duudChains1.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/duudChains1.B > t
diff t TestResults/CSFIActivity/duudChains1.B.out

echo "Testing TestCases/CSFIActivity/externalCalls1.B, TestResults/CSFIActivity/externalCalls1.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/externalCalls1.B > t
diff t TestResults/CSFIActivity/externalCalls1.B.out

echo "Testing TestCases/CSFIActivity/externalCalls2.B, TestResults/CSFIActivity/externalCalls2.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/externalCalls2.B > t
diff t TestResults/CSFIActivity/externalCalls2.B.out

echo "Testing TestCases/CSFIActivity/float_intrinsic.B, TestResults/CSFIActivity/float_intrinsic.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/float_intrinsic.B > t
diff t TestResults/CSFIActivity/float_intrinsic.B.out

echo "Testing TestCases/CSFIActivity/gcmBit1.B, TestResults/CSFIActivity/gcmBit1.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/gcmBit1.B > t
diff t TestResults/CSFIActivity/gcmBit1.B.out

echo "Testing TestCases/CSFIActivity/globalActive_4.B, TestResults/CSFIActivity/globalActive_4.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/globalActive_4.B > t
diff t TestResults/CSFIActivity/globalActive_4.B.out

echo "Testing TestCases/CSFIActivity/globalActive_5.B, TestResults/CSFIActivity/globalActive_5.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/globalActive_5.B > t
diff t TestResults/CSFIActivity/globalActive_5.B.out

echo "Testing TestCases/CSFIActivity/globalActive_6.B, TestResults/CSFIActivity/globalActive_6.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/globalActive_6.B > t
diff t TestResults/CSFIActivity/globalActive_6.B.out

echo "Testing TestCases/CSFIActivity/globalActive_8.B, TestResults/CSFIActivity/globalActive_8.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/globalActive_8.B > t
diff t TestResults/CSFIActivity/globalActive_8.B.out

echo "Testing TestCases/CSFIActivity/If_Loop_4.B, TestResults/CSFIActivity/If_Loop_4.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/If_Loop_4.B > t
diff t TestResults/CSFIActivity/If_Loop_4.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_10.B, TestResults/CSFIActivity/Loop_simple_10.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_10.B > t
diff t TestResults/CSFIActivity/Loop_simple_10.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_11.B, TestResults/CSFIActivity/Loop_simple_11.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_11.B > t
diff t TestResults/CSFIActivity/Loop_simple_11.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_1a.B, TestResults/CSFIActivity/Loop_simple_1a.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_1a.B > t
diff t TestResults/CSFIActivity/Loop_simple_1a.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_1b.B, TestResults/CSFIActivity/Loop_simple_1b.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_1b.B > t
diff t TestResults/CSFIActivity/Loop_simple_1b.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_1c.B, TestResults/CSFIActivity/Loop_simple_1c.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_1c.B > t
diff t TestResults/CSFIActivity/Loop_simple_1c.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_1d.B, TestResults/CSFIActivity/Loop_simple_1d.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_1d.B > t
diff t TestResults/CSFIActivity/Loop_simple_1d.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_1e.B, TestResults/CSFIActivity/Loop_simple_1e.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_1e.B > t
diff t TestResults/CSFIActivity/Loop_simple_1e.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_1f.B, TestResults/CSFIActivity/Loop_simple_1f.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_1f.B > t
diff t TestResults/CSFIActivity/Loop_simple_1f.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_4a.B, TestResults/CSFIActivity/Loop_simple_4a.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_4a.B > t
diff t TestResults/CSFIActivity/Loop_simple_4a.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_4b.B, TestResults/CSFIActivity/Loop_simple_4b.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_4b.B > t
diff t TestResults/CSFIActivity/Loop_simple_4b.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_4c.B, TestResults/CSFIActivity/Loop_simple_4c.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_4c.B > t
diff t TestResults/CSFIActivity/Loop_simple_4c.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_7.B, TestResults/CSFIActivity/Loop_simple_7.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_7.B > t
diff t TestResults/CSFIActivity/Loop_simple_7.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_8.B, TestResults/CSFIActivity/Loop_simple_8.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_8.B > t
diff t TestResults/CSFIActivity/Loop_simple_8.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_9.B, TestResults/CSFIActivity/Loop_simple_9.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_9.B > t
diff t TestResults/CSFIActivity/Loop_simple_9.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_9a.B, TestResults/CSFIActivity/Loop_simple_9a.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_9a.B > t
diff t TestResults/CSFIActivity/Loop_simple_9a.B.out

echo "Testing TestCases/CSFIActivity/Loop_simple_9b.B, TestResults/CSFIActivity/Loop_simple_9b.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/Loop_simple_9b.B > t
diff t TestResults/CSFIActivity/Loop_simple_9b.B.out

echo "Testing TestCases/CSFIActivity/mini1.B, TestResults/CSFIActivity/mini1.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/mini1.B > t
diff t TestResults/CSFIActivity/mini1.B.out

echo "Testing TestCases/CSFIActivity/nested_dfdcfj.B, TestResults/CSFIActivity/nested_dfdcfj.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/nested_dfdcfj.B > t
diff t TestResults/CSFIActivity/nested_dfdcfj.B.out

echo "Testing TestCases/CSFIActivity/NestedIfLoop.B, TestResults/CSFIActivity/NestedIfLoop.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/NestedIfLoop.B > t
diff t TestResults/CSFIActivity/NestedIfLoop.B.out

echo "Testing TestCases/CSFIActivity/RoehFlux.B, TestResults/CSFIActivity/RoehFlux.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/RoehFlux.B > t
diff t TestResults/CSFIActivity/RoehFlux.B.out

echo "Testing TestCases/CSFIActivity/RoehFlux_MemOps.B, TestResults/CSFIActivity/RoehFlux_MemOps.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/RoehFlux_MemOps.B > t
diff t TestResults/CSFIActivity/RoehFlux_MemOps.B.out

echo "Testing TestCases/CSFIActivity/todd.B, TestResults/CSFIActivity/todd.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/todd.B > t
diff t TestResults/CSFIActivity/todd.B.out

echo "Testing TestCases/CSFIActivity/todd1.B, TestResults/CSFIActivity/todd1.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/todd1.B > t
diff t TestResults/CSFIActivity/todd1.B.out

echo "Testing TestCases/CSFIActivity/u_def_struct_1.B, TestResults/CSFIActivity/u_def_struct_1.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/u_def_struct_1.B > t
diff t TestResults/CSFIActivity/u_def_struct_1.B.out

echo "Testing TestCases/CSFIActivity/u_def_struct_2.B, TestResults/CSFIActivity/u_def_struct_2.B.out "
./test-open64 --oa-CSFIActivity TestCases/CSFIActivity/u_def_struct_2.B > t
diff t TestResults/CSFIActivity/u_def_struct_2.B.out

