${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/UDDUChains/UDDUChainConditional.f
mv UDDUChainConditional.B TestCases/UDDUChains/UDDUChainConditional.B
echo "Testing TestCases/UDDUChains/UDDUChainConditional.B, TestResults/UDDUChains/UDDUChainConditional.B.out Checked by PLM 05/04/08"
./test-open64 --oa-UDDUChains TestCases/UDDUChains/UDDUChainConditional.B > t
diff -I "LOC 0 0 source files:" t TestResults/UDDUChains/UDDUChainConditional.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/UDDUChains/UDDUChainInterProcedural1.f
mv UDDUChainInterProcedural1.B TestCases/UDDUChains/UDDUChainInterProcedural1.B
echo "Testing TestCases/UDDUChains/UDDUChainInterProcedural1.B, TestResults/UDDUChains/UDDUChainInterProcedural1.B.out Checked by PLM 05/04/08"
./test-open64 --oa-UDDUChains TestCases/UDDUChains/UDDUChainInterProcedural1.B > t
diff -I "LOC 0 0 source files:" t TestResults/UDDUChains/UDDUChainInterProcedural1.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/UDDUChains/UDDUChainNestedGlobals.f
mv UDDUChainNestedGlobals.B TestCases/UDDUChains/UDDUChainNestedGlobals.B
echo "Testing TestCases/UDDUChains/UDDUChainNestedGlobals.B, TestResults/UDDUChains/UDDUChainNestedGlobals.B.out Checked by PLM 05/05/08"
./test-open64 --oa-UDDUChains TestCases/UDDUChains/UDDUChainNestedGlobals.B > t
diff -I "LOC 0 0 source files:" t TestResults/UDDUChains/UDDUChainNestedGlobals.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/UDDUChains/UDDUChainIndirect1.f
mv UDDUChainIndirect1.B TestCases/UDDUChains/UDDUChainIndirect1.B
echo "Testing TestCases/UDDUChains/UDDUChainIndirect1.B, TestResults/UDDUChains/UDDUChainIndirect1.B.out Checked by PLM 05/05/08"
./test-open64 --oa-UDDUChains TestCases/UDDUChains/UDDUChainIndirect1.B > t
diff -I "LOC 0 0 source files:" t TestResults/UDDUChains/UDDUChainIndirect1.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/UDDUChains/UDDUChainInterProcedural2.f
mv UDDUChainInterProcedural2.B TestCases/UDDUChains/UDDUChainInterProcedural2.B
echo "Testing TestCases/UDDUChains/UDDUChainInterProcedural2.B, TestResults/UDDUChains/UDDUChainInterProcedural2.B.out Checked by PLM 05/04/08"
./test-open64 --oa-UDDUChains TestCases/UDDUChains/UDDUChainInterProcedural2.B > t
diff -I "LOC 0 0 source files:" t TestResults/UDDUChains/UDDUChainInterProcedural2.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/UDDUChains/UDDUChainIndirect2.f
mv UDDUChainIndirect2.B TestCases/UDDUChains/UDDUChainIndirect2.B
echo "Testing TestCases/UDDUChains/UDDUChainIndirect2.B, TestResults/UDDUChains/UDDUChainIndirect2.B.out Checked by PLM 05/05/08"
./test-open64 --oa-UDDUChains TestCases/UDDUChains/UDDUChainIndirect2.B > t
diff -I "LOC 0 0 source files:" t TestResults/UDDUChains/UDDUChainIndirect2.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/UDDUChains/UDDUChainLoop.f
mv UDDUChainLoop.B TestCases/UDDUChains/UDDUChainLoop.B
echo "Testing TestCases/UDDUChains/UDDUChainLoop.B, TestResults/UDDUChains/UDDUChainLoop.B.out Checked by PLM 05/04/08"
./test-open64 --oa-UDDUChains TestCases/UDDUChains/UDDUChainLoop.B > t
diff -I "LOC 0 0 source files:" t TestResults/UDDUChains/UDDUChainLoop.B.out

