${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/activity_int5.f
mv activity_int5.B TestCases/Activity/activity_int5.B
echo "Testing TestCases/Activity/activity_int5.B, TestResults/ICFGActive/activity_int5.B.out Tested by PLM 05/02/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/activity_int5.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGActive/activity_int5.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/argumentArrayIndex3.f
mv argumentArrayIndex3.B TestCases/Activity/argumentArrayIndex3.B
echo "Testing TestCases/Activity/argumentArrayIndex3.B, TestResults/ICFGActive/argumentArrayIndex3.B.out Tested by PLM 05/02/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/argumentArrayIndex3.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGActive/argumentArrayIndex3.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/activity_proc_call1.f
mv activity_proc_call1.B TestCases/Activity/activity_proc_call1.B
echo "Testing TestCases/Activity/activity_proc_call1.B, TestResults/ICFGActive/activity_proc_call1.B.out Tested by PLM 04/02/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/activity_proc_call1.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGActive/activity_proc_call1.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/simple_if2.f
mv simple_if2.B TestCases/Activity/simple_if2.B
echo "Testing TestCases/Activity/simple_if2.B, TestResults/ICFGActive/simple_if2.B.out Tested by PLM 04/02/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/simple_if2.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGActive/simple_if2.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/sideEffect_3.f
mv sideEffect_3.B TestCases/Activity/sideEffect_3.B
echo "Testing TestCases/Activity/sideEffect_3.B, TestResults/ICFGActive/sideEffect_3.B.out Tested by PLM 04/02/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/sideEffect_3.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGActive/sideEffect_3.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/multiple_calls1.f
mv multiple_calls1.B TestCases/Activity/multiple_calls1.B
echo "Testing TestCases/Activity/multiple_calls1.B, TestResults/ICFGActive/multiple_calls1.B.out Tested by PLM 04/02/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/multiple_calls1.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGActive/multiple_calls1.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/multiple_calls2.f
mv multiple_calls2.B TestCases/Activity/multiple_calls2.B
echo "Testing TestCases/Activity/multiple_calls2.B, TestResults/ICFGActive/multiple_calls2.B.out Tested by PLM 04/02/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/multiple_calls2.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGActive/multiple_calls2.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/multiple_calls3.f
mv multiple_calls3.B TestCases/Activity/multiple_calls3.B
echo "Testing TestCases/Activity/multiple_calls3.B, TestResults/ICFGActive/multiple_calls3.B.out Tested by MMS 08/04/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/multiple_calls3.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGActive/multiple_calls3.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/multiple_calls4.f
mv multiple_calls4.B TestCases/Activity/multiple_calls4.B
echo "Testing TestCases/Activity/multiple_calls4.B, TestResults/ICFGActive/multiple_calls4.B.out Tested by MMS 08/04/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/multiple_calls4.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGActive/multiple_calls4.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/Activity/actualAsExpression.f
mv actualAsExpression.B TestCases/Activity/actualAsExpression.B
echo "Testing TestCases/Activity/actualAsExpression.B, TestResults/ICFGActive/actualAsExpression.B.out Tested by PLM 05/17/08"
./test-open64 --oa-ICFGActivity TestCases/Activity/actualAsExpression.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGActive/actualAsExpression.B.out

