echo "Testing TestCases/UDDUChainsTestsXAIF/reachdef_if1.B, TestResults/UDDUChainsTestsXAIF/reachdef_if1.B.out "
./test-open64 --oa-UDDUChainsXAIF TestCases/UDDUChainsTestsXAIF/reachdef_if1.B > t
diff t TestResults/UDDUChainsTestsXAIF/reachdef_if1.B.out

echo "Testing TestCases/UDDUChainsTestsXAIF/reachdef_if2.B, TestResults/UDDUChainsTestsXAIF/reachdef_if2.B.out "
./test-open64 --oa-UDDUChainsXAIF TestCases/UDDUChainsTestsXAIF/reachdef_if2.B > t
diff t TestResults/UDDUChainsTestsXAIF/reachdef_if2.B.out

echo "Testing TestCases/UDDUChainsTestsXAIF/reachdef_loopif1.B, TestResults/UDDUChainsTestsXAIF/reachdef_loopif1.B.out "
./test-open64 --oa-UDDUChainsXAIF TestCases/UDDUChainsTestsXAIF/reachdef_loopif1.B > t
diff t TestResults/UDDUChainsTestsXAIF/reachdef_loopif1.B.out

echo "Testing TestCases/UDDUChainsTestsXAIF/interalias_proc_call1.B, TestResults/UDDUChainsTestsXAIF/interalias_proc_call1.B.out "
./test-open64 --oa-UDDUChainsXAIF TestCases/UDDUChainsTestsXAIF/interalias_proc_call1.B > t
diff t TestResults/UDDUChainsTestsXAIF/interalias_proc_call1.B.out

