${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagCSFIAlias/multiple_calls3.f
mv -f multiple_calls3.B TestCases/AliasTagCSFIAlias/multiple_calls3.B
echo "Testing TestCases/AliasTagCSFIAlias/multiple_calls3.B, TestResults/CallContexts/multiple_calls3.B.out Checked by  BK 08/06/09"
./test-open64 --oa-CallContexts TestCases/AliasTagCSFIAlias/multiple_calls3.B > t
diff -I "LOC 0 0 source files:" t TestResults/CallContexts/multiple_calls3.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagCSFIAlias/multiple_calls7.f
mv -f multiple_calls7.B TestCases/AliasTagCSFIAlias/multiple_calls7.B
echo "Testing TestCases/AliasTagCSFIAlias/multiple_calls7.B, TestResults/CallContexts/multiple_calls7.B.out Checked by  BK 08/06/09"
./test-open64 --oa-CallContexts TestCases/AliasTagCSFIAlias/multiple_calls7.B > t
diff -I "LOC 0 0 source files:" t TestResults/CallContexts/multiple_calls7.B.out

