echo "Testing TestCases/Alias/interalias_proc_call1.B, TestResults/AliasMapInter/interalias_proc_call1.B.out not relevant anymore"
./test-open64 --oa-AliasMapInter TestCases/Alias/interalias_proc_call1.B > t
diff t TestResults/AliasMapInter/interalias_proc_call1.B.out

echo "Testing TestCases/Alias/interalias_proc_call2.B, TestResults/AliasMapInter/interalias_proc_call2.B.out not relevant anymore"
./test-open64 --oa-AliasMapInter TestCases/Alias/interalias_proc_call2.B > t
diff t TestResults/AliasMapInter/interalias_proc_call2.B.out

echo "Testing TestCases/Alias/interalias_proc_call3.B, TestResults/AliasMapInter/interalias_proc_call3.B.out not relevant anymore"
./test-open64 --oa-AliasMapInter TestCases/Alias/interalias_proc_call3.B > t
diff t TestResults/AliasMapInter/interalias_proc_call3.B.out

