${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagCSFIAlias/conditional.f
mv conditional.B TestCases/AliasTagCSFIAlias/conditional.B
echo "Testing TestCases/AliasTagCSFIAlias/conditional.B, TestResults/AliasTagCSFIAlias/conditional.B.out Checked by  ??? ??/??/09"
./test-open64 --oa-AliasTagCSFIAlias TestCases/AliasTagCSFIAlias/conditional.B > t
diff -I "LOC 0 0 source files:" t TestResults/AliasTagCSFIAlias/conditional.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/AliasTagCSFIAlias/multiple_calls3.f
mv multiple_calls3.B TestCases/AliasTagCSFIAlias/multiple_calls3.B
echo "Testing TestCases/AliasTagCSFIAlias/multiple_calls3.B, TestResults/AliasTagCSFIAlias/multiple_calls3.B.out Checked by ??? ??/??/09"
./test-open64 --oa-AliasTagCSFIAlias TestCases/AliasTagCSFIAlias/multiple_calls3.B > t
diff -I "LOC 0 0 source files:" t TestResults/AliasTagCSFIAlias/multiple_calls3.B.out

