echo "Testing TestCases/Alias/interalias_proc_call1.B, TestResults/AliasMapFIAlias/interalias_proc_call1.B.out rechecked by MMS 8/1/06"
./test-open64 --oa-AliasMapFIAlias TestCases/Alias/interalias_proc_call1.B > t
diff t TestResults/AliasMapFIAlias/interalias_proc_call1.B.out

echo "Testing TestCases/Alias/interalias_proc_call2.B, TestResults/AliasMapFIAlias/interalias_proc_call2.B.out rechecked by MMS 8/1/06"
./test-open64 --oa-AliasMapFIAlias TestCases/Alias/interalias_proc_call2.B > t
diff t TestResults/AliasMapFIAlias/interalias_proc_call2.B.out

echo "Testing TestCases/Alias/interalias_proc_call3.B, TestResults/AliasMapFIAlias/interalias_proc_call3.B.out rechecked by MMS 8/1/06"
./test-open64 --oa-AliasMapFIAlias TestCases/Alias/interalias_proc_call3.B > t
diff t TestResults/AliasMapFIAlias/interalias_proc_call3.B.out

