${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/ReachConsts/constprop_if1a.f90
mv constprop_if1a.B TestCases/ReachConsts/constprop_if1a.B
echo "Testing TestCases/ReachConsts/constprop_if1a.B, TestResults/ICFGReachConsts/constprop_if1a.B.out Checked by BK 07/17/08"
./test-open64 --oa-ICFGReachConsts TestCases/ReachConsts/constprop_if1a.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGReachConsts/constprop_if1a.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/ReachConsts/constprop_if1.f90
mv constprop_if1.B TestCases/ReachConsts/constprop_if1.B
echo "Testing TestCases/ReachConsts/constprop_if1.B, TestResults/ICFGReachConsts/constprop_if1.B.out Checked by BK 07/17/08"
./test-open64 --oa-ICFGReachConsts TestCases/ReachConsts/constprop_if1.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGReachConsts/constprop_if1.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/ReachConsts/constprop_if1b.f90
mv constprop_if1b.B TestCases/ReachConsts/constprop_if1b.B
echo "Testing TestCases/ReachConsts/constprop_if1b.B, TestResults/ICFGReachConsts/constprop_if1b.B.out Checked by BK 07/17/08"
./test-open64 --oa-ICFGReachConsts TestCases/ReachConsts/constprop_if1b.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGReachConsts/constprop_if1b.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/ReachConsts/constprop_if1c.f90
mv constprop_if1c.B TestCases/ReachConsts/constprop_if1c.B
echo "Testing TestCases/ReachConsts/constprop_if1c.B, TestResults/ICFGReachConsts/constprop_if1c.B.out Checked by BK 07/17/08"
./test-open64 --oa-ICFGReachConsts TestCases/ReachConsts/constprop_if1c.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGReachConsts/constprop_if1c.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/ReachConsts/constprop_loop1.f90
mv constprop_loop1.B TestCases/ReachConsts/constprop_loop1.B
echo "Testing TestCases/ReachConsts/constprop_loop1.B, TestResults/ICFGReachConsts/constprop_loop1.B.out Checked by BK 07/17/08"
./test-open64 --oa-ICFGReachConsts TestCases/ReachConsts/constprop_loop1.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGReachConsts/constprop_loop1.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/ReachConsts/constprop_loop2.f90
mv constprop_loop2.B TestCases/ReachConsts/constprop_loop2.B
echo "Testing TestCases/ReachConsts/constprop_loop2.B, TestResults/ICFGReachConsts/constprop_loop2.B.out Checked by BK 07/17/08"
./test-open64 --oa-ICFGReachConsts TestCases/ReachConsts/constprop_loop2.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGReachConsts/constprop_loop2.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/ReachConsts/constprop_proc1.f90
mv constprop_proc1.B TestCases/ReachConsts/constprop_proc1.B
echo "Testing TestCases/ReachConsts/constprop_proc1.B, TestResults/ICFGReachConsts/constprop_proc1.B.out Checked by BK 07/17/08"
./test-open64 --oa-ICFGReachConsts TestCases/ReachConsts/constprop_proc1.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGReachConsts/constprop_proc1.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/ReachConsts/constprop_proc2.f90
mv constprop_proc2.B TestCases/ReachConsts/constprop_proc2.B
echo "Testing TestCases/ReachConsts/constprop_proc2.B, TestResults/ICFGReachConsts/constprop_proc2.B.out Checked by BK 07/17/08"
./test-open64 --oa-ICFGReachConsts TestCases/ReachConsts/constprop_proc2.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGReachConsts/constprop_proc2.B.out

${OPEN64TARG}/crayf90/sgi/mfef90 -z -F -N132 TestCases/ReachConsts/constprop_proc3.f90
mv constprop_proc3.B TestCases/ReachConsts/constprop_proc3.B
echo "Testing TestCases/ReachConsts/constprop_proc3.B, TestResults/ICFGReachConsts/constprop_proc3.B.out Checked by BK 07/17/08"
./test-open64 --oa-ICFGReachConsts TestCases/ReachConsts/constprop_proc3.B > t
diff -I "LOC 0 0 source files:" t TestResults/ICFGReachConsts/constprop_proc3.B.out

