echo "Testing TestCases/ReachDefs/interalias_proc_call3_rd.B, TestResults/ReachDefsCFG/interalias_proc_call3_rd.B.out Checked By LMR 6/28/2006"
./test-open64 --oa-CFG TestCases/ReachDefs/interalias_proc_call3_rd.B > t
diff t TestResults/ReachDefsCFG/interalias_proc_call3_rd.B.out

echo "Testing TestCases/ReachDefs/reachdef_if1.B, TestResults/ReachDefsCFG/reachdef_if1.B.out Checked By LMR 6/28/2006"
./test-open64 --oa-CFG TestCases/ReachDefs/reachdef_if1.B > t
diff t TestResults/ReachDefsCFG/reachdef_if1.B.out

echo "Testing TestCases/ReachDefs/reachdef_if2.B, TestResults/ReachDefsCFG/reachdef_if2.B.out Checked By LMR 6/27/2006"
./test-open64 --oa-CFG TestCases/ReachDefs/reachdef_if2.B > t
diff t TestResults/ReachDefsCFG/reachdef_if2.B.out

echo "Testing TestCases/ReachDefs/reachdef_loopif1.B, TestResults/ReachDefsCFG/reachdef_loopif1.B.out Checked By LMR 6/27/2006"
./test-open64 --oa-CFG TestCases/ReachDefs/reachdef_loopif1.B > t
diff t TestResults/ReachDefsCFG/reachdef_loopif1.B.out

