echo "Testing TestCases/UseMREs/formalarray.B, TestResults/UseMREs/formalarray.B.out Checked by PLM 10/15/07"
./test-open64 --oa-UseMREs TestCases/UseMREs/formalarray.B > t
diff t TestResults/UseMREs/formalarray.B.out

echo "Testing TestCases/UseMREs/formalstructpointer.B, TestResults/UseMREs/formalstructpointer.B.out Checked by PLM 10/15/07"
./test-open64 --oa-UseMREs TestCases/UseMREs/formalstructpointer.B > t
diff t TestResults/UseMREs/formalstructpointer.B.out

echo "Testing TestCases/UseMREs/localpointerToscalar.B, TestResults/UseMREs/localpointerToscalar.B.out Checked by PLM 10/15/07"
./test-open64 --oa-UseMREs TestCases/UseMREs/localpointerToscalar.B > t
diff t TestResults/UseMREs/localpointerToscalar.B.out

echo "Testing TestCases/UseMREs/formalpointerToArray.B, TestResults/UseMREs/formalpointerToArray.B.out Checked by PLM 10/15/07"
./test-open64 --oa-UseMREs TestCases/UseMREs/formalpointerToArray.B > t
diff t TestResults/UseMREs/formalpointerToArray.B.out

echo "Testing TestCases/UseMREs/formalstructvar.B, TestResults/UseMREs/formalstructvar.B.out Checked by PLM 10/15/07"
./test-open64 --oa-UseMREs TestCases/UseMREs/formalstructvar.B > t
diff t TestResults/UseMREs/formalstructvar.B.out

echo "Testing TestCases/UseMREs/localscalar.B, TestResults/UseMREs/localscalar.B.out Checked by PLM 10/15/07"
./test-open64 --oa-UseMREs TestCases/UseMREs/localscalar.B > t
diff t TestResults/UseMREs/localscalar.B.out

echo "Testing TestCases/UseMREs/formalpointerToscalar.B, TestResults/UseMREs/formalpointerToscalar.B.out Checked by PLM 10/15/07"
./test-open64 --oa-UseMREs TestCases/UseMREs/formalpointerToscalar.B > t
diff t TestResults/UseMREs/formalpointerToscalar.B.out

echo "Testing TestCases/UseMREs/localarray.B, TestResults/UseMREs/localarray.B.out Checked by PLM 10/15/07"
./test-open64 --oa-UseMREs TestCases/UseMREs/localarray.B > t
diff t TestResults/UseMREs/localarray.B.out

echo "Testing TestCases/UseMREs/localstructpointer.B, TestResults/UseMREs/localstructpointer.B.out Checked by PLM 10/15/07"
./test-open64 --oa-UseMREs TestCases/UseMREs/localstructpointer.B > t
diff t TestResults/UseMREs/localstructpointer.B.out

echo "Testing TestCases/UseMREs/formalscalar.B, TestResults/UseMREs/formalscalar.B.out Checked by PLM 10/15/07"
./test-open64 --oa-UseMREs TestCases/UseMREs/formalscalar.B > t
diff t TestResults/UseMREs/formalscalar.B.out

echo "Testing TestCases/UseMREs/localpointerToArray.B, TestResults/UseMREs/localpointerToArray.B.out Checked by PLM 10/15/07"
./test-open64 --oa-UseMREs TestCases/UseMREs/localpointerToArray.B > t
diff t TestResults/UseMREs/localpointerToArray.B.out

echo "Testing TestCases/UseMREs/localstructvar.B, TestResults/UseMREs/localstructvar.B.out Checked by PLM 10/15/07"
./test-open64 --oa-UseMREs TestCases/UseMREs/localstructvar.B > t
diff t TestResults/UseMREs/localstructvar.B.out

