echo "Testing TestCases/UDDUChainsTests/reachdef_if1.B, TestResults/UDDUChainsTests/reachdef_if1.B.out Checked by PLM 10/20/06"
./test-open64 --oa-UDDUChains TestCases/UDDUChainsTests/reachdef_if1.B > t
diff t TestResults/UDDUChainsTests/reachdef_if1.B.out

echo "Testing TestCases/UDDUChainsTests/reachdef_if2.B, TestResults/UDDUChainsTests/reachdef_if2.B.out Checked by PLM 10/20/06"
./test-open64 --oa-UDDUChains TestCases/UDDUChainsTests/reachdef_if2.B > t
diff t TestResults/UDDUChainsTests/reachdef_if2.B.out

echo "Testing TestCases/UDDUChainsTests/reachdef_loopif1.B, TestResults/UDDUChainsTests/reachdef_loopif1.B.out Checked by PLM 10/20/06"
./test-open64 --oa-UDDUChains TestCases/UDDUChainsTests/reachdef_loopif1.B > t
diff t TestResults/UDDUChainsTests/reachdef_loopif1.B.out

echo "Testing TestCases/UDDUChainsTests/Loop_simple_10.B, TestResults/UDDUChainsTests/Loop_simple_10.B.out Checked by PLM 04/18/07"
./test-open64 --oa-UDDUChains TestCases/UDDUChainsTests/Loop_simple_10.B > t
diff t TestResults/UDDUChainsTests/Loop_simple_10.B.out

