      SUBROUTINE PVAP(I,T,PVRES)
C
C USED TO BE     FUNCTION PVAP(I,T)
C     ******************
C
C         VAPOR PRESSURE (K(I)*P OF COMPONENT I AT TEMPERATURE T (F)
C         WRITTEN BY R.R.HUGHES         EES IDENT SP/PVAP
C              LAST REVISION MAY 9, 1974
C
       COMMON /UNPT/ JOUT,KNTRL,KFLAG,NCP,NPTP,NCST,NREC,NEN,WTEN(5),
     1  WEN(5,12),PTPEN(5,6),COST(5),EN(100),KTLN(15)
c     COMMON /ACT/ WTEN(5),WEN(5,12),PTPEN(5,6),COST(5),EN(100)
c     COMMON /UNACT/ JOUT,KNTRL,KFLAG,NPTP,NCST,NREC,NEN,NCP,KTLN(15)
      COMMON /QP/ CSXX(12,28),ANAMC(12,6)
      DIMENSION A(12),B(12),C(12)
C      EQUIVALENCE (CSXX(1,24),A(1)),(CSXX(1,25),B(1)),(CSXX(1,26),C(1))
C+++++++++++++++++++++++++++++++++++++++++++++++++
      REAL PVRES
      DATA PLMIN/-38./,PLMAX/38./
C
        TC = (T-32.)/1.8
C              ANTOINE EQUATION
      PLIQ=CSXX(I,24)-CSXX(I,25)/(TC+CSXX(I,26))
      IF(PLIQ.LT.PLMAX)GO TO 15
      PVRES=1.E10
      GO TO 90
15    IF(PLIQ.GT.PLMIN) GO TO 10
        PVRES=0.
      GO TO 90
C            CONVERT UNITS AND CALCULATE THE VAPOR PRESSURE
  10    PVRES= 0.019336842*10.**PLIQ
  90  RETURN
      END
