C
      SUBROUTINE WTMOL(JW)
C     ********************
C
C        SPAD SUBROUTINE FOR CALCULATING AVG MOL WT OF A STREAM WITH
C        COMPONENT MOLAL FLOWS WEN(JW,I) AND TOTAL MOLAL FLOW WTEN(JW)
C        (WTEN WILL BE CALCULATED IF ENTRY IS ZERO)
C                                      EES IDENT SP/WTMOL
C        WRITTEN BY R. R. HUGHES
C             LAST REVISION AUG. 1 , 1973
C
      LOGICAL MDO
      COMMON /UNPT/ JOUT,KNTRL,KFLAG,NCPS,NPTP,NCST,NREC,NEN,WTEN(5),
     1  WEN(5,12),PTPEN(5,6),COST(5),EN(100),KTLN(15)
c     COMMON /ACT/ WTEN(5),WEN(5,12),PTPEN(5,6),COST(5),EN(100)
c     COMMON /UNACT/ JOUT,KNTRL,KFLAG,NPTP,NCST,NREC,NEN,NCPS,KTLN(15)
      COMMON/QP/CSXX(12,28),ANAMC(12,6)
C            CHECK THE TOTAL FLOW
      IF(WTEN(JW).LE.1.0E-10) GO TO 30
C
      MDO=.FALSE.
      GO TO 40
30    MDO=.TRUE.
      WTEN(JW)=0.
40    WM=0.
C
      DO 70 I=1,NCPS
C           CALCULATE THE TOTAL FLOW, IF NECESSARY
      IF(MDO)WTEN(JW)=WTEN(JW)+WEN(JW,I)
C           SUM THE MOLECULAR WEIGHTS OF EACH COMPONENT
      WM=WM+WEN(JW,I)*CSXX(I,6)
70    CONTINUE
C
      IF(WTEN(JW).LE.0.)GO TO 80
C           CALCULATE THE AVERAGE MOLECULAR WEIGHT OF STREAM JW
      PTPEN(JW,6)=WM/WTEN(JW)
75    RETURN
C           ZERO FLOW MEANS ZERO MOLECULAR WEIGHT
80    PTPEN (JW,6)=0.
      GO TO 75
C
      END
