          ACT0 = K - 1
          MAX0 = NR
          ACT1 = BI - MYBXLO(MYTHID)
          MAX1 = MYBXHI(MYTHID) - MYBXLO(MYTHID) + 1
          ACT2 = BJ - MYBYLO(MYTHID)
          MAX2 = MYBYHI(MYTHID) - MYBYLO(MYTHID) + 1
          ACT3 = MYTHID - 1
          MAX3 = NTX*NTY
          ACT4 = IKEY_DYNAMICS - 1
          IMOMKEY = (ACT0 + 1)                    + ACT1*MAX0                    + ACT2*MAX0*MAX1                    + ACT3*MAX0*MAX1*MAX2                    + ACT4*MAX0*MAX1*MAX2*MAX3
      DO J=1-OLY,SNY+OLY
       DO I=1-OLX,SNX+OLX
        VF(I,J)   = 0.
        V4F(I,J)  = 0.
        CF(I,J)   = 0.
        MT(I,J)   = 0.
        FZON(I,J) = 0.
        FMER(I,J) = 0.
        FVRUP(I,J)= 0.
        FVRDW(I,J)= 0.
        RTRANSU(I,J)= 0.
        RTRANSV(I,J)= 0.
        STRAIN(I,J) = 0.
        TENSION(I,J)= 0.
        GUDISS(I,J) = 0.
        GVDISS(I,J) = 0.
        VORT3(I,J)   = 0.D0
        STRAIN(I,J)  = 0.D0
        TENSION(I,J) = 0.D0
       ENDDO
      ENDDO
      UDUDXFAC     = AFFACMOM*1.
      AHDUDXFAC    = VFFACMOM*1.
      VDUDYFAC     = AFFACMOM*1.
      AHDUDYFAC    = VFFACMOM*1.
      RVELDUDRFAC  = AFFACMOM*1.
      ARDUDRFAC    = VFFACMOM*1.
      MTFACU       = MTFACMOM*1.
      MTNHFACU     = 1.
      FUFAC        = CFFACMOM*1.
      UDVDXFAC     = AFFACMOM*1.
      AHDVDXFAC    = VFFACMOM*1.
      VDVDYFAC     = AFFACMOM*1.
      AHDVDYFAC    = VFFACMOM*1.
      RVELDVDRFAC  = AFFACMOM*1.
      ARDVDRFAC    = VFFACMOM*1.
      MTFACV       = MTFACMOM*1.
      MTNHFACV     = 1.
      FVFAC        = CFFACMOM*1.
      IF (IMPLICITVISCOSITY) THEN
        ARDUDRFAC  = 0.
        ARDVDRFAC  = 0.
      ENDIF
      IF ( NO_SLIP_SIDES ) THEN
        SIDEMASKFAC = SIDEDRAGFACTOR
      ELSE
        SIDEMASKFAC = 0.D0
      ENDIF
      IF (     NO_SLIP_BOTTOM    .OR. BOTTOMDRAGQUADRATIC.NE.0.    .OR. BOTTOMDRAGLINEAR.NE.0.) THEN
       BOTTOMDRAGTERMS=.TRUE.
      ELSE
       BOTTOMDRAGTERMS=.FALSE.
      ENDIF
      CALL MOM_CALC_HFACZ(BI,BJ,K,HFACZ,R_HFACZ,MYTHID)
      DO J=1-OLY,SNY+OLY
       DO I=1-OLX,SNX+OLX
        XA(I,J) = DYG(I,J,BI,BJ)   *DRF(K)*HFACW(I,J,K,BI,BJ)
        YA(I,J) = DXG(I,J,BI,BJ)   *DRF(K)*HFACS(I,J,K,BI,BJ)
       ENDDO
      ENDDO
      DO J=1-OLY,SNY+OLY
       DO I=1-OLX,SNX+OLX
        UFLD(I,J) = UVEL(I,J,K,BI,BJ)
        VFLD(I,J) = VVEL(I,J,K,BI,BJ)
       ENDDO
      ENDDO
      DO J=1-OLY,SNY+OLY
       DO I=1-OLX,SNX+OLX
        UTRANS(I,J) = UFLD(I,J)*XA(I,J)
        VTRANS(I,J) = VFLD(I,J)*YA(I,J)
       ENDDO
      ENDDO
      CALL MOM_CALC_KE(BI,BJ,K,2,UFLD,VFLD,KE,MYTHID)
      IF ( MOMVISCOSITY) THEN
        CALL MOM_CALC_HDIV(BI,BJ,K,2,UFLD,VFLD,HDIV,MYTHID)
        CALL MOM_CALC_RELVORT3(BI,BJ,K,UFLD,VFLD,HFACZ,VORT3,MYTHID)
        CALL MOM_CALC_TENSION(BI,BJ,K,UFLD,VFLD,TENSION,MYTHID)
        CALL MOM_CALC_STRAIN(BI,BJ,K,UFLD,VFLD,HFACZ,STRAIN,MYTHID)
        DO J=1-OLY,SNY+OLY
         DO I=1-OLX,SNX+OLX
           IF ( HFACZ(I,J).EQ.0. ) THEN
             VORT3(I,J)  = SIDEMASKFAC*VORT3(I,J)
             STRAIN(I,J) = SIDEMASKFAC*STRAIN(I,J)
           ENDIF
         ENDDO
        ENDDO
      ENDIF
      IF (MOMADVECTION.AND.K.EQ.1) THEN
        CALL MOM_CALC_RTRANS( K, BI, BJ,                        RTRANSU, RTRANSV,                        MYTIME, MYITER, MYTHID)
        CALL MOM_U_ADV_WU( BI,BJ,K,UVEL,WVEL,RTRANSU,                     FVERU(1-OLX,1-OLY,KUP), MYTHID )
        CALL MOM_V_ADV_WV( BI,BJ,K,VVEL,WVEL,RTRANSV,                     FVERV(1-OLX,1-OLY,KUP), MYTHID )
      ENDIF
      IF (MOMADVECTION) THEN
        CALL MOM_CALC_RTRANS( K+1, BI, BJ,                        RTRANSU, RTRANSV,                        MYTIME, MYITER, MYTHID)
      ENDIF
      IF (MOMVISCOSITY) THEN
       CALL MOM_CALC_VISC(        BI,BJ,K,        VISCAH_Z,VISCAH_D,VISCA4_Z,VISCA4_D,        HARMONIC,BIHARMONIC,USEVARIABLEVISCOSITY,        HDIV,VORT3,TENSION,STRAIN,KE,HFACZ,        MYTHID)
      ENDIF
      IF (MOMADVECTION) THEN
        CALL MOM_U_ADV_UU(BI,BJ,K,UTRANS,UFLD,FZON,MYTHID)
        CALL MOM_U_ADV_VU(BI,BJ,K,VTRANS,UFLD,FMER,MYTHID)
        CALL MOM_U_ADV_WU(                     BI,BJ,K+1,UVEL,WVEL,RTRANSU,                     FVERU(1-OLX,1-OLY,KDOWN), MYTHID )
        DO J=JMIN,JMAX
         DO I=IMIN,IMAX
          GU(I,J,K,BI,BJ) =     -RECIP_HFACW(I,J,K,BI,BJ)*RECIP_DRF(K)     *RECIP_RAW(I,J,BI,BJ)    *( ( FZON(I,J  )     - FZON(I-1,J) )*UDUDXFAC      +( FMER(I,J+1)     - FMER(I,  J) )*VDUDYFAC      +(FVERU(I,J,KDOWN) - FVERU(I,J,KUP))*RKSIGN*RVELDUDRFAC     )
         ENDDO
        ENDDO
      ELSE
        DO J=1-OLY,SNY+OLY
         DO I=1-OLX,SNX+OLX
           GU(I,J,K,BI,BJ) = 0.D0
         ENDDO
        ENDDO
      ENDIF
      IF (MOMVISCOSITY) THEN
        IF (BIHARMONIC)  CALL MOM_U_DEL2U(BI,BJ,K,UFLD,HFACZ,V4F,MYTHID)
        CALL MOM_U_XVISCFLUX(BI,BJ,K,UFLD,V4F,FZON,    VISCAH_D,VISCA4_D,MYTHID)
        CALL MOM_U_YVISCFLUX(BI,BJ,K,UFLD,V4F,HFACZ,FMER,    VISCAH_Z,VISCA4_Z,MYTHID)
       IF (.NOT.IMPLICITVISCOSITY) THEN
        CALL MOM_U_RVISCFLUX(BI,BJ, K, UVEL,KAPPARU,FVRUP,MYTHID)
        CALL MOM_U_RVISCFLUX(BI,BJ,K+1,UVEL,KAPPARU,FVRDW,MYTHID)
       ENDIF
        DO J=JMIN,JMAX
         DO I=IMIN,IMAX
          GUDISS(I,J) =     -RECIP_HFACW(I,J,K,BI,BJ)*RECIP_DRF(K)     *RECIP_RAW(I,J,BI,BJ)    *( ( FZON(I,J  ) - FZON(I-1,J) )*AHDUDXFAC      +( FMER(I,J+1) - FMER(I,  J) )*AHDUDYFAC      +( FVRDW(I,J)  - FVRUP(I,J) )*RKSIGN*ARDUDRFAC     )
         ENDDO
        ENDDO
        IF (NO_SLIP_SIDES) THEN
         CALL MOM_U_SIDEDRAG(        BI,BJ,K,        UFLD, V4F, HFACZ,        VISCAH_Z,VISCA4_Z,        HARMONIC,BIHARMONIC,USEVARIABLEVISCOSITY,        VF,        MYTHID)
         DO J=JMIN,JMAX
          DO I=IMIN,IMAX
           GUDISS(I,J) = GUDISS(I,J) + VF(I,J)
          ENDDO
         ENDDO
        ENDIF
        IF (BOTTOMDRAGTERMS) THEN
         CALL MOM_U_BOTTOMDRAG(BI,BJ,K,UFLD,KE,KAPPARU,VF,MYTHID)
         DO J=JMIN,JMAX
          DO I=IMIN,IMAX
           GUDISS(I,J) = GUDISS(I,J) + VF(I,J)
          ENDDO
         ENDDO
        ENDIF
      ENDIF
      IF (USENHMTERMS) THEN
       CALL MOM_U_METRIC_NH(BI,BJ,K,UFLD,WVEL,MT,MYTHID)
       DO J=JMIN,JMAX
        DO I=IMIN,IMAX
         GU(I,J,K,BI,BJ) = GU(I,J,K,BI,BJ)+MTNHFACU*MT(I,J)
        ENDDO
       ENDDO
      ENDIF
      IF ( USINGSPHERICALPOLARGRID .AND. METRICTERMS ) THEN
       CALL MOM_U_METRIC_SPHERE(BI,BJ,K,UFLD,VFLD,MT,MYTHID)
       DO J=JMIN,JMAX
        DO I=IMIN,IMAX
         GU(I,J,K,BI,BJ) = GU(I,J,K,BI,BJ)+MTFACU*MT(I,J)
        ENDDO
       ENDDO
      ENDIF
      IF ( USINGCYLINDRICALGRID .AND. METRICTERMS ) THEN
       CALL MOM_U_METRIC_CYLINDER(BI,BJ,K,UFLD,VFLD,MT,MYTHID)
       DO J=JMIN,JMAX
        DO I=IMIN,IMAX
         GU(I,J,K,BI,BJ) = GU(I,J,K,BI,BJ)+MTFACU*MT(I,J)
        ENDDO
       ENDDO
      ENDIF
      IF (MOMADVECTION) THEN
        CALL MOM_V_ADV_UV(BI,BJ,K,UTRANS,VFLD,FZON,MYTHID)
        CALL MOM_V_ADV_VV(BI,BJ,K,VTRANS,VFLD,FMER,MYTHID)
        CALL MOM_V_ADV_WV(                     BI,BJ,K+1,VVEL,WVEL,RTRANSV,                     FVERV(1-OLX,1-OLY,KDOWN), MYTHID )
        DO J=JMIN,JMAX
         DO I=IMIN,IMAX
          GV(I,J,K,BI,BJ) =     -RECIP_HFACS(I,J,K,BI,BJ)*RECIP_DRF(K)      *RECIP_RAS(I,J,BI,BJ)    *( ( FZON(I+1,J)     - FZON(I,J  ) )*UDVDXFAC      +( FMER(I,  J)     - FMER(I,J-1) )*VDVDYFAC      +(FVERV(I,J,KDOWN) - FVERV(I,J,KUP))*RKSIGN*RVELDVDRFAC     )
         ENDDO
        ENDDO
      ELSE
        DO J=1-OLY,SNY+OLY
         DO I=1-OLX,SNX+OLX
           GV(I,J,K,BI,BJ) = 0.D0
         ENDDO
        ENDDO
      ENDIF
      IF (MOMVISCOSITY) THEN
        IF (BIHARMONIC)  CALL MOM_V_DEL2V(BI,BJ,K,VFLD,HFACZ,V4F,MYTHID)
        CALL MOM_V_XVISCFLUX(BI,BJ,K,VFLD,V4F,HFACZ,FZON,    VISCAH_Z,VISCA4_Z,MYTHID)
        CALL MOM_V_YVISCFLUX(BI,BJ,K,VFLD,V4F,FMER,    VISCAH_D,VISCA4_D,MYTHID)
       IF (.NOT.IMPLICITVISCOSITY) THEN
        CALL MOM_V_RVISCFLUX(BI,BJ, K, VVEL,KAPPARV,FVRUP,MYTHID)
        CALL MOM_V_RVISCFLUX(BI,BJ,K+1,VVEL,KAPPARV,FVRDW,MYTHID)
       ENDIF
        DO J=JMIN,JMAX
         DO I=IMIN,IMAX
          GVDISS(I,J) =     -RECIP_HFACS(I,J,K,BI,BJ)*RECIP_DRF(K)      *RECIP_RAS(I,J,BI,BJ)    *( ( FZON(I+1,J)  - FZON(I,J  ) )*AHDVDXFAC      +( FMER(I,  J)  - FMER(I,J-1) )*AHDVDYFAC      +( FVRDW(I,J)   - FVRUP(I,J) )*RKSIGN*ARDVDRFAC     )
         ENDDO
        ENDDO
        IF (NO_SLIP_SIDES) THEN
         CALL MOM_V_SIDEDRAG(        BI,BJ,K,        VFLD, V4F, HFACZ,        VISCAH_Z,VISCA4_Z,        HARMONIC,BIHARMONIC,USEVARIABLEVISCOSITY,        VF,        MYTHID)
         DO J=JMIN,JMAX
          DO I=IMIN,IMAX
           GVDISS(I,J) = GVDISS(I,J) + VF(I,J)
          ENDDO
         ENDDO
        ENDIF
        IF (BOTTOMDRAGTERMS) THEN
         CALL MOM_V_BOTTOMDRAG(BI,BJ,K,VFLD,KE,KAPPARV,VF,MYTHID)
         DO J=JMIN,JMAX
          DO I=IMIN,IMAX
           GVDISS(I,J) = GVDISS(I,J) + VF(I,J)
          ENDDO
         ENDDO
        ENDIF
      ENDIF
      IF (USENHMTERMS) THEN
       CALL MOM_V_METRIC_NH(BI,BJ,K,VFLD,WVEL,MT,MYTHID)
       DO J=JMIN,JMAX
        DO I=IMIN,IMAX
         GV(I,J,K,BI,BJ) = GV(I,J,K,BI,BJ)+MTNHFACV*MT(I,J)
        ENDDO
       ENDDO
      ENDIF
      IF ( USINGSPHERICALPOLARGRID .AND. METRICTERMS ) THEN
       CALL MOM_V_METRIC_SPHERE(BI,BJ,K,UFLD,MT,MYTHID)
       DO J=JMIN,JMAX
        DO I=IMIN,IMAX
         GV(I,J,K,BI,BJ) = GV(I,J,K,BI,BJ)+MTFACV*MT(I,J)
        ENDDO
       ENDDO
      ENDIF
      IF ( USINGCYLINDRICALGRID .AND. METRICTERMS ) THEN
       CALL MOM_V_METRIC_CYLINDER(BI,BJ,K,UFLD,VFLD,MT,MYTHID)
       DO J=JMIN,JMAX
        DO I=IMIN,IMAX
         GV(I,J,K,BI,BJ) = GV(I,J,K,BI,BJ)+MTFACV*MT(I,J)
        ENDDO
       ENDDO
      ENDIF
      IF (.NOT.USECDSCHEME) THEN
        CALL MOM_U_CORIOLIS(BI,BJ,K,VFLD,CF,MYTHID)
        DO J=JMIN,JMAX
         DO I=IMIN,IMAX
          GU(I,J,K,BI,BJ) = GU(I,J,K,BI,BJ)+FUFAC*CF(I,J)
         ENDDO
        ENDDO
        CALL MOM_V_CORIOLIS(BI,BJ,K,UFLD,CF,MYTHID)
        DO J=JMIN,JMAX
         DO I=IMIN,IMAX
          GV(I,J,K,BI,BJ) = GV(I,J,K,BI,BJ)+FVFAC*CF(I,J)
         ENDDO
        ENDDO
      ENDIF
      IF ( USE3DCORIOLIS ) THEN
        CALL MOM_U_CORIOLIS_NH(BI,BJ,K,WVEL,CF,MYTHID)
        DO J=JMIN,JMAX
         DO I=IMIN,IMAX
          GU(I,J,K,BI,BJ) = GU(I,J,K,BI,BJ)+FUFAC*CF(I,J)
         ENDDO
        ENDDO
       IF ( USINGCURVILINEARGRID ) THEN
        CALL MOM_V_CORIOLIS_NH(BI,BJ,K,WVEL,CF,MYTHID)
        DO J=JMIN,JMAX
         DO I=IMIN,IMAX
          GV(I,J,K,BI,BJ) = GV(I,J,K,BI,BJ)+FVFAC*CF(I,J)
         ENDDO
        ENDDO
       ENDIF
      ENDIF
      DO J=JMIN,JMAX
       DO I=IMIN,IMAX
        GU(I,J,K,BI,BJ) = GU(I,J,K,BI,BJ)*MASKW(I,J,K,BI,BJ)
        GUDISS(I,J)     = GUDISS(I,J)    *MASKW(I,J,K,BI,BJ)
        GV(I,J,K,BI,BJ) = GV(I,J,K,BI,BJ)*MASKS(I,J,K,BI,BJ)
        GVDISS(I,J)     = GVDISS(I,J)    *MASKS(I,J,K,BI,BJ)
       ENDDO
      ENDDO
      RETURN
      END
