aifl: aifl.o dnsty.o hdel.o hmx.o hvap.o iflash.o main.o pvap.o tbtd.o tset.o vmgas.o vmliq.o wtmol.o
	f77 -o aifl aifl.o dnsty.o hdel.o hmx.o hvap.o iflash.o main.o pvap.o tbtd.o tset.o vmgas.o vmliq.o wtmol.o

